default: &default
  adapter: mysql2
  pool: 5
  username: <%= ENV['NMCORE_DATABASE_USER'] %>
  password: <%= ENV['NMCORE_DATABASE_PASSWORD'] %>
  host: <%= ENV['NMCORE_DATABASE_HOST'] %>
  port: 3306

development:
  <<: *default
  database: numedik_development

test:
  <<: *default
  database: numedik_test

production:
  <<: *default
  database: <%= ENV['NMCORE_DB_NAME'] %>
