# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3215f194a1ab0cae8e22e70c902071f6d495283a9459ac4d9144c5ff775cee2220bf119c38b159e10403bd90db0a65fb6aafebad5ee5298ab617204f073ca9

test:
  secret_key_base: 9a0ad7ea6860ace225c7d6c75a1af6ba1e7391a69107a4a230933266b8c9c918aa195eed8619b9ea63daec8ff8fe13b2b87b27954ceecb8e34c59846f1d584e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
