# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(username: 'abh', email: 'abh@numedik.com', password: 'abh' )

Store.create(id:1, code: 'MS', name: 'Main Store')
Accounttype.create(id:1, code: 'G', name: 'General')
Plan.create(id:1, code: 'N', name: 'Normal Rate')


Drugdosage.create( id: 1, code: 'TAB', name: 'TABLET', disabled: false)
Drugdosage.create( id: 2, code: 'SUPP', name: 'SUPP', disabled: false)
Drugdosage.create( id: 4, code: 'AMP', name: 'AMP', disabled: false)
Drugdosage.create( id: 5, code: 'CC', name: 'ML', disabled: false)
Drugdosage.create( id: 6, code: 'CRM', name: 'CRM', disabled: false)
Drugdosage.create( id: 7, code: 'DROP', name: 'DROP', disabled: false)
Drugdosage.create( id: 8, code: 'LA', name: 'LA', disabled: false)
Drugdosage.create( id: 9, code: 'ORAL', name: 'ORAL', disabled: false)
Drugdosage.create( id: 10, code: 'PACK', name: 'PACK', disabled: false)
Drugdosage.create( id: 14, code: 'OZ', name: 'OZ', disabled: false)
Drugdosage.create( id: 15, code: 'TUBE', name: 'TUBE', disabled: false)
Drugdosage.create( id: 16, code: 'JAR', name: 'JAR', disabled: false)
Drugdosage.create( id: 17, code: 'IU', name: 'IU', disabled: false)
Drugdosage.create( id: 18, code: 'ML', name: 'ML', disabled: false)
Drugdosage.create( id: 19, code: 'SAC', name: 'SACHET', disabled: false)
Drugdosage.create( id: 20, code: 'BOX', name: 'BOX', disabled: false)
Drugdosage.create( id: 21, code: 'BAG', name: 'BAG', disabled: false)
Drugdosage.create( id: 22, code: 'BOT', name: 'BOT', disabled: false)
Drugdosage.create( id: 23, code: 'PCS', name: 'PIECES', disabled: false)
Drugdosage.create( id: 24, code: 'PTCH', name: 'PTCH', disabled: false)
Drugdosage.create( id: 25, code: 'KI.U', name: 'KI.U', disabled: false)
Drugdosage.create( id: 26, code: 'I.U.', name: 'I.U.', disabled: false)
Drugdosage.create( id: 27, code: 'SET', name: 'SET', disabled: false)
Drugdosage.create( id: 28, code: 'PESS', name: 'PESS', disabled: false)
Drugdosage.create( id: 29, code: 'GM', name: 'GM', disabled: false)
Drugdosage.create( id: 30, code: 'PAIR', name: 'PAIR', disabled: false)
Drugdosage.create( id: 31, code: 'UNIT', name: 'UNIT', disabled: false)
Drugdosage.create( id: 32, code: 'TIN', name: 'TIN', disabled: false)
Drugdosage.create( id: 33, code: 'CAN', name: 'CAN', disabled: false)
Drugdosage.create( id: 34, code: 'DISK', name: 'DISK', disabled: false)
Drugdosage.create( id: 35, code: 'TEST', name: 'TEST', disabled: false)
Drugdosage.create( id: 36, code: 'CCS', name: 'CCS', disabled: false)
Drugdosage.create( id: 37, code: 'CART', name: 'CART', disabled: false)
Drugdosage.create( id: 38, code: 'MTR', name: 'MTR', disabled: false)
Drugdosage.create( id: 39, code: 'STRP', name: 'STRIP', disabled: false)
Drugdosage.create( id: 40, code: 'BAR', name: 'BAR', disabled: false)
Drugdosage.create( id: 41, code: 'ROLL', name: 'ROLL', disabled: false)
Drugdosage.create( id: 42, code: 'BTL', name: 'BTL', disabled: false)
Drugdosage.create( id: 43, code: 'BX', name: 'BX', disabled: false)
Drugdosage.create( id: 44, code: 'CM', name: 'CM', disabled: false)
Drugdosage.create( id: 45, code: 'MLS', name: 'MLS', disabled: false)
Drugdosage.create( id: 3, code: 'CAP', name: 'CAPSULE', disabled: false)
Drugdosage.create( id: 13, code: 'VIAL', name: 'VIAL', disabled: false)
Drugdosage.create( id: 12, code: 'PUFF', name: 'PUFF', disabled: false)
Drugdosage.create( id: 11, code: 'PAST', name: 'PAST', disabled: false)

Drugroute.create( id: 1, code: 'SYRUP', name: 'MINUM', disabled: false)
Drugroute.create( id: 2, code: 'PO', name: 'MAKAN', disabled: false)
Drugroute.create( id: 3, code: 'EAR-DROP', name: 'TITIK KE DALAM TELINGA', disabled: false)
Drugroute.create( id: 4, code: 'EYES-DROP', name: 'TITIK KE DALAM MATA', disabled: false)
Drugroute.create( id: 5, code: 'IM', name: 'INTRA MUSCULAR', disabled: false)
Drugroute.create( id: 6, code: 'INHALE', name: 'SEDUT DALAM MULUT', disabled: false)
Drugroute.create( id: 7, code: 'LA', name: 'SAPU', disabled: false)
Drugroute.create( id: 8, code: 'LA MOUTH', name: 'ORAL AID', disabled: false)
Drugroute.create( id: 9, code: 'NOSE-DROP', name: 'TITIK KE DALAM HIDUNG', disabled: false)
Drugroute.create( id: 10, code: 'OD', name: 'SEKALI SEHARI', disabled: false)
Drugroute.create( id: 12, code: 'SUPP', name: 'MASUKKAN KE DALAM PUNGGUNG', disabled: false)
Drugroute.create( id: 14, code: 'GARGLE', name: 'KUMUR', disabled: false)
Drugroute.create( id: 15, code: 'BANDAGE', name: 'BALUT DI TEMPAT BERKENAAN', disabled: false)
Drugroute.create( id: 16, code: 'IV', name: 'INTRAVENOUS', disabled: false)
Drugroute.create( id: 17, code: 'SC', name: 'SUBCUTAENOUS', disabled: false)
Drugroute.create( id: 18, code: 'SHAMPOO', name: 'CUCI DI KEPALA', disabled: false)
Drugroute.create( id: 19, code: 'VAGINA', name: 'MASUK KE DALAM VAGINA', disabled: false)
Drugroute.create( id: 20, code: 'PATCH', name: 'TAMPAL ', disabled: false)
Drugroute.create( id: 21, code: 'HISAP', name: 'HISAP', disabled: false)
Drugroute.create( id: 22, code: 'DRESSING', name: 'CUCI DI TEMPAT BERKENAAN', disabled: false)
Drugroute.create( id: 23, code: 'CHEW', name: 'KUNYAH', disabled: false)
Drugroute.create( id: 24, code: 'IN EYE', name: 'SAPU DALAM MATA', disabled: false)
Drugroute.create( id: 25, code: 'SUBLINGUAL', name: 'LETAK BAWAH LIDAH', disabled: false)
Drugroute.create( id: 26, code: 'SUCK', name: 'HISAP', disabled: false)
Drugroute.create( id: 27, code: 'INJECT', name: 'SUNTIKAN', disabled: false)
Drugroute.create( id: 28, code: 'SPRAY NOSE', name: 'SEMBUR KE DALAM HIDUNG', disabled: false)
Drugroute.create( id: 29, code: 'SOLUBLE', name: 'BANCUH DALAM AIR', disabled: false)
Drugroute.create( id: 30, code: 'URINE DIPSTICK', name: 'CELUP STRIP DALAM URINE', disabled: false)
Drugroute.create( id: 31, code: 'INTRADERMAL', name: 'INTRADERMAL', disabled: false)
Drugroute.create( id: 32, code: 'TDM', name: 'TITIK DALAM MULUT', disabled: false)


Drugstrength.create( id: 1, code: 'MG', name: 'mg', disabled: false)
Drugstrength.create( id: 2, code: '%', name: '%', disabled: false)
Drugstrength.create( id: 3, code: 'cc', name: 'cc', disabled: false)
Drugstrength.create( id: 4, code: 'mg/ml', name: 'mg/ml', disabled: false)
Drugstrength.create( id: 5, code: 'mg/5ml', name: 'mg/5ml', disabled: false)
Drugstrength.create( id: 6, code: 'g', name: 'g', disabled: false)
Drugstrength.create( id: 7, code: 'gm', name: 'gm', disabled: false)
Drugstrength.create( id: 8, code: 'iu/3ml', name: 'iu/3ml', disabled: false)
Drugstrength.create( id: 9, code: 'mcg', name: 'mcg', disabled: false)
Drugstrength.create( id: 10, code: 'mg/2ml', name: 'mg/2ml', disabled: false)
Drugstrength.create( id: 11, code: 'mg/cc', name: 'mg/cc', disabled: false)
Drugstrength.create( id: 12, code: 'ml', name: 'ml', disabled: false)
Drugstrength.create( id: 13, code: 'oz', name: 'OZ', disabled: false)

Drugtype.create( id: 1, code: 'TB', name: 'TABLET', disabled: false)
Drugtype.create( id: 2, code: 'SY', name: 'SYRUP', disabled: false)
Drugtype.create( id: 3, code: 'CR', name: 'CREAM', disabled: false)
Drugtype.create( id: 5, code: 'DI', name: 'DISPOSABLE', disabled: false)
Drugtype.create( id: 7, code: 'SFTGEL', name: 'SOFT GEL', disabled: false)
Drugtype.create( id: 8, code: 'SUPP', name: 'SUPP', disabled: false)
Drugtype.create( id: 6, code: 'CAPS', name: 'CAPSULE', disabled: false)
Drugtype.create( id: 4, code: 'INJ', name: 'INJECTION', disabled: false)

Gender.create( id: 1, code: 'M', name: 'MALE', disabled: false)
Gender.create( id: 2, code: 'F', name: 'FEMALE', disabled: false)
Gender.create( id: 3, code: 'U', name: 'UNKNOWN', disabled: false)

Patienttype.create( id: 1, code: 'OP', name: 'Out Patient', disabled: false)
Patienttype.create( id: 2, code: 'IP', name: 'In Patient', disabled: false)
Patienttype.create( id: 3, code: 'AE', name: 'Emergency', disabled: false)
Patienttype.create( id: 4, code: 'RT', name: 'Retails', disabled: false)

Nationality.create( id: 1, code: 'MY', name: 'Malaysian', disabled: false)
Nationality.create( id: 2, code: 'TR', name: 'Temporary Residents', disabled: false)
Nationality.create( id: 3, code: 'PR', name: 'Permanent Residents', disabled: false)
Nationality.create( id: 4, code: 'ETC', name: 'Others', disabled: false)

Religion.create( id: 1, code: 'MS', name: 'Muslim', disabled: false)
Religion.create( id: 2, code: 'BD', name: 'Buddha', disabled: false)
Religion.create( id: 3, code: 'HD', name: 'Hindu', disabled: false)
Religion.create( id: 4, code: 'SK', name: 'Sikhism', disabled: false)
Religion.create( id: 5, code: 'AT', name: 'Atheists ', disabled: false)
Religion.create( id: 6, code: 'ETC', name: 'Others', disabled: false)
Religion.create( id: 7, code: 'K', name: 'Christian', disabled: false)

Marital.create( id: 1, code: 'S', name: 'Single', disabled: false)
Marital.create( id: 2, code: 'M', name: 'Married', disabled: false)
Marital.create( id: 5, code: 'NIL', name: 'Unknown', disabled: false)
Marital.create( id: 3, code: 'WD', name: 'Widow', disabled: false)
Marital.create( id: 4, code: 'WW', name: 'Widower', disabled: false)

Bloodtype.create( id: 1, code: 'O-', name: 'O- NEGATIVE', disabled: false)
Bloodtype.create( id: 2, code: 'O+', name: 'O+ POSITIVE', disabled: false)
Bloodtype.create( id: 3, code: 'A+', name: 'A+ POSITIVE', disabled: false)
Bloodtype.create( id: 4, code: 'B-', name: 'B- NEGATIVE', disabled: false)
Bloodtype.create( id: 5, code: 'A-', name: 'A- NEGATIVE', disabled: false)
Bloodtype.create( id: 6, code: 'B+', name: 'B+ POSITIVE', disabled: false)
Bloodtype.create( id: 7, code: 'U', name: 'UNSPECIFIED', disabled: false)

State.create( id: 1, code: 'KELANTAN', name: 'KELANTAN', disabled: false)
State.create( id: 2, code: 'KEDAH', name: 'KEDAH', disabled: false)
State.create( id: 3, code: 'KUALA LUMPUR', name: 'KUALA LUMPUR', disabled: false)
State.create( id: 4, code: 'JOHOR', name: 'JOHOR', disabled: false)
State.create( id: 5, code: 'MELAKA', name: 'MELAKA', disabled: false)
State.create( id: 6, code: 'NEGERI SEMBILAN', name: 'NEGERI SEMBILAN', disabled: false)
State.create( id: 7, code: 'PAHANG', name: 'PAHANG', disabled: false)
State.create( id: 8, code: 'PENANG', name: 'PENANG', disabled: false)
State.create( id: 9, code: 'PERAK', name: 'PERAK', disabled: false)
State.create( id: 10, code: 'PERLIS', name: 'PERLIS', disabled: false)
State.create( id: 11, code: 'SABAH', name: 'SABAH', disabled: false)
State.create( id: 12, code: 'SARAWAK', name: 'SARAWAK', disabled: false)
State.create( id: 13, code: 'SELANGOR', name: 'SELANGOR', disabled: false)
State.create( id: 14, code: 'TERENGGANU', name: 'TERENGGANU', disabled: false)
State.create( id: 15, code: 'AMERICA', name: 'AMERICA', disabled: false)
State.create( id: 16, code: 'AUSTRALIA', name: 'AUSTRALIA', disabled: false)
State.create( id: 17, code: 'BANGLADESH', name: 'BANGLADESH', disabled: false)
State.create( id: 18, code: 'BURMA', name: 'BURMA', disabled: false)
State.create( id: 19, code: 'CHINA', name: 'CHINA', disabled: false)
State.create( id: 20, code: 'PHILIPPINES', name: 'PHILIPPINES', disabled: false)
State.create( id: 21, code: 'INDONESIA', name: 'INDONESIA', disabled: false)
State.create( id: 22, code: 'JAPAN', name: 'JAPAN', disabled: false)
State.create( id: 23, code: 'CAMBODIA', name: 'CAMBODIA', disabled: false)
State.create( id: 24, code: 'KOREA', name: 'KOREA', disabled: false)
State.create( id: 25, code: 'PAKISTAN', name: 'PAKISTAN', disabled: false)
State.create( id: 26, code: 'SINGAPORE', name: 'SINGAPORE', disabled: false)
State.create( id: 27, code: 'THAILAND', name: 'THAILAND', disabled: false)
State.create( id: 28, code: 'UNITED KINGDOM', name: 'UNITED KINGDOM', disabled: false)
State.create( id: 29, code: 'OTHERS', name: 'OTHERS', disabled: false)
State.create( id: 30, code: 'INDIA', name: 'INDIA', disabled: false)

Designation.create( id: 1, code: 'en', name: 'Encik', disabled: false)
Designation.create( id: 2, code: 'cik', name: 'Cik', disabled: false)
Designation.create( id: 3, code: 'tn', name: 'Tuan', disabled: false)
Designation.create( id: 4, code: 'pn', name: 'Puan', disabled: false)
Designation.create( id: 5, code: 'hj', name: 'Haji', disabled: false)
Designation.create( id: 6, code: 'hjh', name: 'Hajah', disabled: false)
Designation.create( id: 7, code: 'dto', name: 'Dato', disabled: false)
Designation.create( id: 8, code: 'dtk', name: 'Datuk', disabled: false)
Designation.create( id: 9, code: 'dtkseri', name: 'Datuk Seri', disabled: false)
Designation.create( id: 10, code: 'dtn', name: 'Datin', disabled: false)
Designation.create( id: 11, code: 'dtnseri', name: 'Datin Seri', disabled: false)
Designation.create( id: 12, code: 'tun', name: 'Tun', disabled: false)
Designation.create( id: 13, code: 'tsri', name: 'Tan Sri', disabled: false)
Designation.create( id: 14, code: 'prof', name: 'Prof.', disabled: false)
Designation.create( id: 15, code: 'profm', name: 'Prof. Madya', disabled: false)
Designation.create( id: 16, code: 'dr', name: 'Dr.', disabled: false)

Rnstat.create( id: 1, code: 'A', name: 'Active', disabled: false)
Rnstat.create( id: 2, code: 'X', name: 'Archive', disabled: false)

Patientstat.create( id: 1, code: 'A', name: 'Active', disabled: false)
Patientstat.create( id: 2, code: 'I', name: 'Inactive', disabled: false)

Treatmentstat.create( id: 1, code: 'N', name: 'New', disabled: false)
Treatmentstat.create( id: 2, code: 'C', name: 'Completed', disabled: false)
Treatmentstat.create( id: 3, code: 'B', name: 'Brough In Dead', disabled: false)

Discipline.create( id: 1, code: 'MEDICAL', name: 'MEDICAL', disabled: false)
Discipline.create( id: 2, code: 'SURGICAL', name: 'SURGICAL', disabled: false)
Discipline.create( id: 3, code: 'OBSTETRIC', name: 'OBSTETRIC', disabled: false)
Discipline.create( id: 4, code: 'PAEDIATRIC', name: 'PAEDIATRIC', disabled: false)
Discipline.create( id: 5, code: 'INFANT', name: 'INFANT', disabled: false)
Discipline.create( id: 6, code: 'UNCLASSIFIED', name: 'UNCLASSIFIED', disabled: false)
Discipline.create( id: 7, code: 'GYNAECOLOGY', name: 'GYNAECOLOGY', disabled: false)
Discipline.create( id: 8, code: 'ORTHOPAEDIC', name: 'ORTHOPAEDIC', disabled: false)
Discipline.create( id: 9, code: 'ENT', name: 'ENT', disabled: false)
Discipline.create( id: 10, code: 'OPHTALMOLOGY', name: 'OPHTALMOLOGY', disabled: false)
Discipline.create( id: 11, code: 'PLASTIC SURGERY', name: 'PLASTIC SURGERY', disabled: false)
Discipline.create( id: 12, code: 'DENTAL', name: 'DENTAL', disabled: false)
Discipline.create( id: 13, code: 'NEUROSURGEON', name: 'NEUROSURGEON', disabled: false)
Discipline.create( id: 14, code: 'ANESTHESIOLOGY', name: 'ANESTHESIOLOGY', disabled: false)
Discipline.create( id: 15, code: 'PSYCHIATRIC', name: 'PSYCHIATRIC', disabled: false)
Discipline.create( id: 16, code: 'RADIOLOGY', name: 'RADIOLOGY', disabled: false)
Discipline.create( id: 17, code: 'GENERAL SURGEON', name: 'GENERAL SURGEON', disabled: false)
Discipline.create( id: 18, code: 'OBSTETRIC & GYNECOLOGY', name: 'OBSTETRIC & GYNECOLOGY', disabled: false)
Discipline.create( id: 19, code: 'MO', name: 'Medical Officer', disabled: false)
Discipline.create( id: 20, code: 'CARDIOLOGY', name: 'CARDIOLOGY', disabled: false)
Discipline.create( id: 21, code: 'UROLOGY', name: 'UROLOGY', disabled: false)

Chargegroup.create( id: 22, code: 'PROCEDURE CHARGES', name: 'PROCEDURE CHARGES', disabled: false)
Chargegroup.create( id: 23, code: 'CSSD CHARGES', name: 'CSSD CHARGES', disabled: false)
Chargegroup.create( id: 24, code: 'OPERATION CHARGES', name: 'OPERATION CHARGES', disabled: false)
Chargegroup.create( id: 25, code: 'CONSULTATION FEES', name: 'CONSULTATION FEES', disabled: false)
Chargegroup.create( id: 26, code: 'ENDOSCOPIC EXAMINATION', name: 'ENDOSCOPIC EXAMINATION', disabled: false)
Chargegroup.create( id: 27, code: 'LABORATORY TESTS', name: 'LABORATORY TESTS', disabled: false)
Chargegroup.create( id: 28, code: 'ULTRASOUND CHARGES', name: 'ULTRASOUND CHARGES', disabled: false)
Chargegroup.create( id: 29, code: 'WARD TESTS', name: 'WARD TESTS', disabled: false)
Chargegroup.create( id: 30, code: 'RADIOLOGY CHARGES', name: 'RADIOLOGY CHARGES', disabled: false)
Chargegroup.create( id: 32, code: 'HOUSE CALL FEE', name: 'HOUSE CALL FEE', disabled: false)
Chargegroup.create( id: 33, code: 'AMBULANCE CHARGES', name: 'AMBULANCE CHARGES', disabled: false)
Chargegroup.create( id: 34, code: 'NURSING CHARGES', name: 'NURSING CHARGES', disabled: false)
Chargegroup.create( id: 35, code: 'HAEMODIALYSIS CHARGES', name: 'HAEMODIALYSIS CHARGES', disabled: false)
Chargegroup.create( id: 36, code: 'NURSERY CHARGES', name: 'NURSERY CHARGES', disabled: false)
Chargegroup.create( id: 37, code: 'LABOUR ROOM CHARGES', name: 'LABOUR ROOM CHARGES', disabled: false)
Chargegroup.create( id: 38, code: 'MISCELLANEOUS CHARGES', name: 'MISCELLANEOUS CHARGES', disabled: false)
Chargegroup.create( id: 39, code: 'CSSD-ORTHO', name: 'CSSD-ORTHO', disabled: false)
Chargegroup.create( id: 40, code: 'OT NURSING', name: 'OT NURSING', disabled: false)
Chargegroup.create( id: 41, code: 'D&C PACKAGE', name: 'D&C PACKAGE', disabled: false)
Chargegroup.create( id: 42, code: 'PHYSIOTHERAPY CHARGES', name: 'PHYSIOTHERAPY CHARGES', disabled: false)
Chargegroup.create( id: 43, code: 'PHARMACEUTICAL CHARGES', name: 'PHARMACEUTICAL CHARGES', disabled: false)
Chargegroup.create( id: 44, code: 'ROUNDING', name: 'ROUNDING', disabled: false)
Chargegroup.create( id: 47, code: 'K.DELV', name: 'DELIVERY PACKAGE', disabled: false)
Chargegroup.create( id: 48, code: 'K.CIRC', name: 'CIRCUMCISION PACKAGE', disabled: false)
Chargegroup.create( id: 49, code: 'K.IUCD', name: 'IUCD PACKAGE', disabled: false)
Chargegroup.create( id: 50, code: 'K.MC01', name: 'PRE-EMPLOYMENT M/CHK', disabled: false)
Chargegroup.create( id: 51, code: 'K.MC02', name: 'SENIOR CITIZEN PCKG', disabled: false)
Chargegroup.create( id: 52, code: 'K.MC03', name: 'EXEC M/CHCK - MO', disabled: false)
Chargegroup.create( id: 53, code: 'K.MC04', name: 'COLLEGE ENTRANCE M/C', disabled: false)
Chargegroup.create( id: 54, code: 'K.MC05', name: 'HAJJ/UMRAH M/CHK', disabled: false)
Chargegroup.create( id: 55, code: 'K.MC06', name: 'EXEC M/CHK - SPCLST', disabled: false)
Chargegroup.create( id: 56, code: 'K.OG01', name: 'ANTENATAL EXAM 1ST', disabled: false)
Chargegroup.create( id: 57, code: 'K.MC07', name: 'FULL EXEC M/CHK-SPCL', disabled: false)
Chargegroup.create( id: 58, code: 'K.OG02', name: 'ANTENATAL EXAM 2ND', disabled: false)
Chargegroup.create( id: 59, code: 'K.OG03', name: 'ANTENATAL EXAM SUBSQ', disabled: false)
Chargegroup.create( id: 60, code: 'K.MC08', name: 'FEMALE MEDICAL EXAM', disabled: false)
Chargegroup.create( id: 61, code: 'K.DLCS', name: 'DELVRY LSCS SPI EMER', disabled: false)
Chargegroup.create( id: 62, code: 'K.DLGA', name: 'DELVRY LSCS EMERGCY', disabled: false)
Chargegroup.create( id: 63, code: 'K.IMMU', name: 'IMMUNIZATION PACKAGE', disabled: false)
Chargegroup.create( id: 64, code: 'K.DLEA', name: 'DELVRY LSCS ELECTIVE', disabled: false)
Chargegroup.create( id: 65, code: 'K.DLES', name: 'DELVRY LSCS SPNAL EL', disabled: false)
Chargegroup.create( id: 66, code: 'K.DLEE', name: 'HERNIOPLASTY PACKAGE', disabled: false)
Chargegroup.create( id: 67, code: 'K.CIRS', name: 'CIRCUM SEDATION PCKG', disabled: false)
Chargegroup.create( id: 68, code: 'DEP', name: 'DEPOSIT', disabled: false)
Chargegroup.create( id: 69, code: 'REG3', name: 'ADMISSION FEE', disabled: false)
Chargegroup.create( id: 70, code: 'REG1', name: 'REGISTRATION FEE 1ST', disabled: false)
Chargegroup.create( id: 71, code: 'REG2', name: 'REGISTRATION FEE SUB', disabled: false)
Chargegroup.create( id: 72, code: 'TAX', name: 'TAX', disabled: false)
Chargegroup.create( id: 45, code: 'MEDICAL SUPPLIES', name: 'MEDICAL SUPPLIES', disabled: false)
Chargegroup.create( id: 74, code: 'INTERNAL FIXATION', name: 'INTERNAL FIXATION', disabled: false)
Chargegroup.create( id: 75, code: 'EXTERNAL FIXATION', name: 'EXTERNAL FIXATION', disabled: false)
Chargegroup.create( id: 77, code: 'AMEX', name: 'AMEX', disabled: false)
Chargegroup.create( id: 82, code: 'CHEQUE', name: 'CHEQUE', disabled: false)
Chargegroup.create( id: 83, code: 'POUT', name: 'PAY 0UT', disabled: false)
Chargegroup.create( id: 76, code: 'ANAESTHETIST FEE', name: 'ANAESTHETIST FEE', disabled: false)
Chargegroup.create( id: 31, code: 'ROOM CHARGES', name: 'ROOM CHARGE', disabled: false)
Chargegroup.create( id: 78, code: 'CASH', name: 'CASH PAYMENT', disabled: false)
Chargegroup.create( id: 79, code: 'CC', name: 'CREDIT CARD', disabled: false)
Chargegroup.create( id: 81, code: 'DB', name: 'DEBIT CARD/BANKCARD', disabled: false)
Chargegroup.create( id: 84, code: 'MEDICAL CHECKUP', name: 'MEDICAL EXAMINATION', disabled: false)
Chargegroup.create( id: 85, code: 'TAKE HOME DRUGS', name: 'TAKE HOME DRUGS', disabled: false)
Chargegroup.create( id: 86, code: 'ANAESTHETIC ASSESMENT', name: 'ANAESTHETIC ASSESMENT', disabled: false)
Chargegroup.create( id: 87, code: 'OPERATING THEATRE', name: 'OPERATING THEATRE', disabled: false)
Chargegroup.create( id: 88, code: 'DEBIT FROM SN', name: 'DEBIT FROM SN', disabled: false)
Chargegroup.create( id: 89, code: 'DEBIT TO SN', name: 'DEBIT TO SN', disabled: false)
Chargegroup.create( id: 90, code: 'DISCOUNT', name: 'DISCOUNT', disabled: false)
Chargegroup.create( id: 91, code: 'XX', name: 'A/R LEDGER', disabled: false)
Chargegroup.create( id: 92, code: 'KBMC', name: 'EXP-', disabled: false)
Chargegroup.create( id: 93, code: 'PATLEDGER', name: 'PATIENT LEDGER', disabled: false)
Chargegroup.create( id: 94, code: 'XXS', name: 'A/R LEDGER (S)', disabled: false)
Chargegroup.create( id: 95, code: 'DIFF', name: 'A/R DIFF', disabled: false)
Chargegroup.create( id: 96, code: 'DTDL', name: 'DEBIT TO DEBTOR LEDGER', disabled: false)
Chargegroup.create( id: 97, code: 'DRAW BLOOD', name: 'DRAW BLOOD', disabled: false)
Chargegroup.create( id: 98, code: 'COLLECT URINE', name: 'COLLECT URINE', disabled: false)
Chargegroup.create( id: 73, code: 'REP', name: 'MEDICAL REPORT', disabled: false)
Chargegroup.create( id: 100, code: 'IBG', name: 'Inter-Bank GIRO (IBG) Transfer', disabled: false)

Billingstat.create( id: 1, code: 'N', name: 'New', disabled: false)
Billingstat.create( id: 2, code: 'C', name: 'Completed', disabled: false)
Billingstat.create( id: 3, code: 'X', name: 'Cancelled', disabled: false)
Billingstat.create( id: 4, code: 'R', name: 'Archive', disabled: false)

Billitemstat.create( id: 1, code: 'A', name: 'Active', disabled: false)
Billitemstat.create( id: 2, code: 'I', name: 'Void', disabled: false)
Billitemstat.create( id: 3, code: 'C', name: 'Clear', disabled: false)
Billitemstat.create( id: 4, code: 'S', name: 'Suspend', disabled: false)

Postat.create( id: 1, code: 'O', name: 'Order', disabled: false)
Postat.create( id: 2, code: 'A', name: 'Acquired', disabled: false)

Drugprocedure.create( id: 1, code: 'A', name: 'Selepas Makan', disabled: false)
Drugprocedure.create( id: 2, code: 'B', name: 'Sebelum Makan', disabled: false)
Drugprocedure.create( id: 3, code: 'C', name: '', disabled: false)

Labresultstat.create( id: 1, code: 'N', name: 'New', disabled: false)
Labresultstat.create( id: 2, code: 'C', name: 'Completed', disabled: false)

Labattachmentstat.create( id: 1, code: 'V', name: 'Valid', disabled: false)
Labattachmentstat.create( id: 2, code: 'I', name: 'Invalid', disabled: false)

Pricetype.create( id: 1, code: 'W', name: 'Warehouse', disabled: false)
Pricetype.create( id: 2, code: 'X', name: 'General', disabled: false)
Pricetype.create( id: 4, code: 'R', name: 'Lab Report', disabled: false)

