# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#rails g model Patient mrn mykadno oldic passport birthcert fullname gender_id:integer add1 add2 add3 city postcode state_id:integer nationality_id:integer homephone mobilephone email dob:date defaultplan_id:integer defaultaccount_id:integer profession employer employerphone religion_id:integer marital_id:integer race_id:integer bloodtype_id:integer patientstat_id:integer remarkgeneral:text remarkallergy:text remarkmedicalhistory:text remarkfamilyhistory:text rnstat_id:integer designation_id:integer relativename relationrelation relativeadd relativetel registrar_id:integer

#rails g model Account code name add1 add2 add3 city postcode state_id:integer accountype_id:integer eligibility:decimal disabled:boolean

#rails g model Treatment sn patient_id:integer patienttype_id:integer treatmentstat_id:integer registrar_id:integer plan_id:integer discipline_id:integer doctor_id:integer legalcase:boolean diagosis:text

User.create(username: 'abh', email: 'abh@numedik.com', password: 'abh' )

Store.create(id:1, code: 'MS', name: 'Main Store')
Accounttype.create(id:1, code: 'G', name: 'General')
Plan.create(id:1, code: 'N', name: 'Normal Rate')


Drugdosage.create( id: 1, code: 'TAB', name: 'TABLET', disabled: false)
Drugdosage.create( id: 2, code: 'SUPP', name: 'SUPP', disabled: false)
Drugdosage.create( id: 4, code: 'AMP', name: 'AMP', disabled: false)
Drugdosage.create( id: 5, code: 'CC', name: 'ML', disabled: false)
Drugdosage.create( id: 6, code: 'CRM', name: 'CRM', disabled: false)
Drugdosage.create( id: 7, code: 'DROP', name: 'DROP', disabled: false)
Drugdosage.create( id: 8, code: 'LA', name: 'LA', disabled: false)
Drugdosage.create( id: 9, code: 'ORAL', name: 'ORAL', disabled: false)
Drugdosage.create( id: 10, code: 'PACK', name: 'PACK', disabled: false)
Drugdosage.create( id: 14, code: 'OZ', name: 'OZ', disabled: false)
Drugdosage.create( id: 15, code: 'TUBE', name: 'TUBE', disabled: false)
Drugdosage.create( id: 16, code: 'JAR', name: 'JAR', disabled: false)
Drugdosage.create( id: 17, code: 'IU', name: 'IU', disabled: false)
Drugdosage.create( id: 18, code: 'ML', name: 'ML', disabled: false)
Drugdosage.create( id: 19, code: 'SAC', name: 'SACHET', disabled: false)
Drugdosage.create( id: 20, code: 'BOX', name: 'BOX', disabled: false)
Drugdosage.create( id: 21, code: 'BAG', name: 'BAG', disabled: false)
Drugdosage.create( id: 22, code: 'BOT', name: 'BOT', disabled: false)
Drugdosage.create( id: 23, code: 'PCS', name: 'PIECES', disabled: false)
Drugdosage.create( id: 24, code: 'PTCH', name: 'PTCH', disabled: false)
Drugdosage.create( id: 25, code: 'KI.U', name: 'KI.U', disabled: false)
Drugdosage.create( id: 26, code: 'I.U.', name: 'I.U.', disabled: false)
Drugdosage.create( id: 27, code: 'SET', name: 'SET', disabled: false)
Drugdosage.create( id: 28, code: 'PESS', name: 'PESS', disabled: false)
Drugdosage.create( id: 29, code: 'GM', name: 'GM', disabled: false)
Drugdosage.create( id: 30, code: 'PAIR', name: 'PAIR', disabled: false)
Drugdosage.create( id: 31, code: 'UNIT', name: 'UNIT', disabled: false)
Drugdosage.create( id: 32, code: 'TIN', name: 'TIN', disabled: false)
Drugdosage.create( id: 33, code: 'CAN', name: 'CAN', disabled: false)
Drugdosage.create( id: 34, code: 'DISK', name: 'DISK', disabled: false)
Drugdosage.create( id: 35, code: 'TEST', name: 'TEST', disabled: false)
Drugdosage.create( id: 36, code: 'CCS', name: 'CCS', disabled: false)
Drugdosage.create( id: 37, code: 'CART', name: 'CART', disabled: false)
Drugdosage.create( id: 38, code: 'MTR', name: 'MTR', disabled: false)
Drugdosage.create( id: 39, code: 'STRP', name: 'STRIP', disabled: false)
Drugdosage.create( id: 40, code: 'BAR', name: 'BAR', disabled: false)
Drugdosage.create( id: 41, code: 'ROLL', name: 'ROLL', disabled: false)
Drugdosage.create( id: 42, code: 'BTL', name: 'BTL', disabled: false)
Drugdosage.create( id: 43, code: 'BX', name: 'BX', disabled: false)
Drugdosage.create( id: 44, code: 'CM', name: 'CM', disabled: false)
Drugdosage.create( id: 45, code: 'MLS', name: 'MLS', disabled: false)
Drugdosage.create( id: 3, code: 'CAP', name: 'CAPSULE', disabled: false)
Drugdosage.create( id: 13, code: 'VIAL', name: 'VIAL', disabled: false)
Drugdosage.create( id: 12, code: 'PUFF', name: 'PUFF', disabled: false)
Drugdosage.create( id: 11, code: 'PAST', name: 'PAST', disabled: false)

Drugroute.create( id: 1, code: 'SYRUP', name: 'MINUM', disabled: false)
Drugroute.create( id: 2, code: 'PO', name: 'MAKAN', disabled: false)
Drugroute.create( id: 3, code: 'EAR-DROP', name: 'TITIK KE DALAM TELINGA', disabled: false)
Drugroute.create( id: 4, code: 'EYES-DROP', name: 'TITIK KE DALAM MATA', disabled: false)
Drugroute.create( id: 5, code: 'IM', name: 'INTRA MUSCULAR', disabled: false)
Drugroute.create( id: 6, code: 'INHALE', name: 'SEDUT DALAM MULUT', disabled: false)
Drugroute.create( id: 7, code: 'LA', name: 'SAPU', disabled: false)
Drugroute.create( id: 8, code: 'LA MOUTH', name: 'ORAL AID', disabled: false)
Drugroute.create( id: 9, code: 'NOSE-DROP', name: 'TITIK KE DALAM HIDUNG', disabled: false)
Drugroute.create( id: 10, code: 'OD', name: 'SEKALI SEHARI', disabled: false)
Drugroute.create( id: 12, code: 'SUPP', name: 'MASUKKAN KE DALAM PUNGGUNG', disabled: false)
Drugroute.create( id: 14, code: 'GARGLE', name: 'KUMUR', disabled: false)
Drugroute.create( id: 15, code: 'BANDAGE', name: 'BALUT DI TEMPAT BERKENAAN', disabled: false)
Drugroute.create( id: 16, code: 'IV', name: 'INTRAVENOUS', disabled: false)
Drugroute.create( id: 17, code: 'SC', name: 'SUBCUTAENOUS', disabled: false)
Drugroute.create( id: 18, code: 'SHAMPOO', name: 'CUCI DI KEPALA', disabled: false)
Drugroute.create( id: 19, code: 'VAGINA', name: 'MASUK KE DALAM VAGINA', disabled: false)
Drugroute.create( id: 20, code: 'PATCH', name: 'TAMPAL ', disabled: false)
Drugroute.create( id: 21, code: 'HISAP', name: 'HISAP', disabled: false)
Drugroute.create( id: 22, code: 'DRESSING', name: 'CUCI DI TEMPAT BERKENAAN', disabled: false)
Drugroute.create( id: 23, code: 'CHEW', name: 'KUNYAH', disabled: false)
Drugroute.create( id: 24, code: 'IN EYE', name: 'SAPU DALAM MATA', disabled: false)
Drugroute.create( id: 25, code: 'SUBLINGUAL', name: 'LETAK BAWAH LIDAH', disabled: false)
Drugroute.create( id: 26, code: 'SUCK', name: 'HISAP', disabled: false)
Drugroute.create( id: 27, code: 'INJECT', name: 'SUNTIKAN', disabled: false)
Drugroute.create( id: 28, code: 'SPRAY NOSE', name: 'SEMBUR KE DALAM HIDUNG', disabled: false)
Drugroute.create( id: 29, code: 'SOLUBLE', name: 'BANCUH DALAM AIR', disabled: false)
Drugroute.create( id: 30, code: 'URINE DIPSTICK', name: 'CELUP STRIP DALAM URINE', disabled: false)
Drugroute.create( id: 31, code: 'INTRADERMAL', name: 'INTRADERMAL', disabled: false)
Drugroute.create( id: 32, code: 'TDM', name: 'TITIK DALAM MULUT', disabled: false)


Drugstrength.create( id: 1, code: 'MG', name: 'mg', disabled: false)
Drugstrength.create( id: 2, code: '%', name: '%', disabled: false)
Drugstrength.create( id: 3, code: 'cc', name: 'cc', disabled: false)
Drugstrength.create( id: 4, code: 'mg/ml', name: 'mg/ml', disabled: false)
Drugstrength.create( id: 5, code: 'mg/5ml', name: 'mg/5ml', disabled: false)
Drugstrength.create( id: 6, code: 'g', name: 'g', disabled: false)
Drugstrength.create( id: 7, code: 'gm', name: 'gm', disabled: false)
Drugstrength.create( id: 8, code: 'iu/3ml', name: 'iu/3ml', disabled: false)
Drugstrength.create( id: 9, code: 'mcg', name: 'mcg', disabled: false)
Drugstrength.create( id: 10, code: 'mg/2ml', name: 'mg/2ml', disabled: false)
Drugstrength.create( id: 11, code: 'mg/cc', name: 'mg/cc', disabled: false)
Drugstrength.create( id: 12, code: 'ml', name: 'ml', disabled: false)
Drugstrength.create( id: 13, code: 'oz', name: 'OZ', disabled: false)

Drugtype.create( id: 1, code: 'TB', name: 'TABLET', disabled: false)
Drugtype.create( id: 2, code: 'SY', name: 'SYRUP', disabled: false)
Drugtype.create( id: 3, code: 'CR', name: 'CREAM', disabled: false)
Drugtype.create( id: 5, code: 'DI', name: 'DISPOSABLE', disabled: false)
Drugtype.create( id: 7, code: 'SFTGEL', name: 'SOFT GEL', disabled: false)
Drugtype.create( id: 8, code: 'SUPP', name: 'SUPP', disabled: false)
Drugtype.create( id: 6, code: 'CAPS', name: 'CAPSULE', disabled: false)
Drugtype.create( id: 4, code: 'INJ', name: 'INJECTION', disabled: false)

Gender.create( id: 1, code: 'M', name: 'MALE', disabled: false)
Gender.create( id: 2, code: 'F', name: 'FEMALE', disabled: false)
Gender.create( id: 3, code: 'U', name: 'UNKNOWN', disabled: false)

Patienttype.create( id: 1, code: 'OP', name: 'Out Patient', disabled: false)
Patienttype.create( id: 2, code: 'IP', name: 'In Patient', disabled: false)
Patienttype.create( id: 3, code: 'AE', name: 'Emergency', disabled: false)
Patienttype.create( id: 4, code: 'RT', name: 'Retails', disabled: false)

Nationality.create( id: 1, code: 'MY', name: 'Malaysian', disabled: false)
Nationality.create( id: 2, code: 'TR', name: 'Temporary Residents', disabled: false)
Nationality.create( id: 3, code: 'PR', name: 'Permanent Residents', disabled: false)
Nationality.create( id: 4, code: 'ETC', name: 'Others', disabled: false)

Religion.create( id: 1, code: 'MS', name: 'Muslim', disabled: false)
Religion.create( id: 2, code: 'BD', name: 'Buddha', disabled: false)
Religion.create( id: 3, code: 'HD', name: 'Hindu', disabled: false)
Religion.create( id: 4, code: 'SK', name: 'Sikhism', disabled: false)
Religion.create( id: 5, code: 'AT', name: 'Atheists ', disabled: false)
Religion.create( id: 6, code: 'ETC', name: 'Others', disabled: false)
Religion.create( id: 7, code: 'K', name: 'Christian', disabled: false)

Marital.create( id: 1, code: 'S', name: 'Single', disabled: false)
Marital.create( id: 2, code: 'M', name: 'Married', disabled: false)
Marital.create( id: 5, code: 'NIL', name: 'Unknown', disabled: false)
Marital.create( id: 3, code: 'WD', name: 'Widow', disabled: false)
Marital.create( id: 4, code: 'WW', name: 'Widower', disabled: false)

Bloodtype.create( id: 1, code: 'O-', name: 'O- NEGATIVE', disabled: false)
Bloodtype.create( id: 2, code: 'O+', name: 'O+ POSITIVE', disabled: false)
Bloodtype.create( id: 3, code: 'A+', name: 'A+ POSITIVE', disabled: false)
Bloodtype.create( id: 4, code: 'B-', name: 'B- NEGATIVE', disabled: false)
Bloodtype.create( id: 5, code: 'A-', name: 'A- NEGATIVE', disabled: false)
Bloodtype.create( id: 6, code: 'B+', name: 'B+ POSITIVE', disabled: false)
Bloodtype.create( id: 7, code: 'U', name: 'UNSPECIFIED', disabled: false)

State.create( id: 1, code: 'KELANTAN', name: 'KELANTAN', disabled: false)
State.create( id: 2, code: 'KEDAH', name: 'KEDAH', disabled: false)
State.create( id: 3, code: 'KUALA LUMPUR', name: 'KUALA LUMPUR', disabled: false)
State.create( id: 4, code: 'JOHOR', name: 'JOHOR', disabled: false)
State.create( id: 5, code: 'MELAKA', name: 'MELAKA', disabled: false)
State.create( id: 6, code: 'NEGERI SEMBILAN', name: 'NEGERI SEMBILAN', disabled: false)
State.create( id: 7, code: 'PAHANG', name: 'PAHANG', disabled: false)
State.create( id: 8, code: 'PENANG', name: 'PENANG', disabled: false)
State.create( id: 9, code: 'PERAK', name: 'PERAK', disabled: false)
State.create( id: 10, code: 'PERLIS', name: 'PERLIS', disabled: false)
State.create( id: 11, code: 'SABAH', name: 'SABAH', disabled: false)
State.create( id: 12, code: 'SARAWAK', name: 'SARAWAK', disabled: false)
State.create( id: 13, code: 'SELANGOR', name: 'SELANGOR', disabled: false)
State.create( id: 14, code: 'TERENGGANU', name: 'TERENGGANU', disabled: false)
State.create( id: 15, code: 'AMERICA', name: 'AMERICA', disabled: false)
State.create( id: 16, code: 'AUSTRALIA', name: 'AUSTRALIA', disabled: false)
State.create( id: 17, code: 'BANGLADESH', name: 'BANGLADESH', disabled: false)
State.create( id: 18, code: 'BURMA', name: 'BURMA', disabled: false)
State.create( id: 19, code: 'CHINA', name: 'CHINA', disabled: false)
State.create( id: 20, code: 'PHILIPPINES', name: 'PHILIPPINES', disabled: false)
State.create( id: 21, code: 'INDONESIA', name: 'INDONESIA', disabled: false)
State.create( id: 22, code: 'JAPAN', name: 'JAPAN', disabled: false)
State.create( id: 23, code: 'CAMBODIA', name: 'CAMBODIA', disabled: false)
State.create( id: 24, code: 'KOREA', name: 'KOREA', disabled: false)
State.create( id: 25, code: 'PAKISTAN', name: 'PAKISTAN', disabled: false)
State.create( id: 26, code: 'SINGAPORE', name: 'SINGAPORE', disabled: false)
State.create( id: 27, code: 'THAILAND', name: 'THAILAND', disabled: false)
State.create( id: 28, code: 'UNITED KINGDOM', name: 'UNITED KINGDOM', disabled: false)
State.create( id: 29, code: 'OTHERS', name: 'OTHERS', disabled: false)
State.create( id: 30, code: 'INDIA', name: 'INDIA', disabled: false)

Designation.create( id: 1, code: 'en', name: 'Encik', disabled: false)
Designation.create( id: 2, code: 'cik', name: 'Cik', disabled: false)
Designation.create( id: 3, code: 'tn', name: 'Tuan', disabled: false)
Designation.create( id: 4, code: 'pn', name: 'Puan', disabled: false)
Designation.create( id: 5, code: 'hj', name: 'Haji', disabled: false)
Designation.create( id: 6, code: 'hjh', name: 'Hajah', disabled: false)
Designation.create( id: 7, code: 'dto', name: 'Dato', disabled: false)
Designation.create( id: 8, code: 'dtk', name: 'Datuk', disabled: false)
Designation.create( id: 9, code: 'dtkseri', name: 'Datuk Seri', disabled: false)
Designation.create( id: 10, code: 'dtn', name: 'Datin', disabled: false)
Designation.create( id: 11, code: 'dtnseri', name: 'Datin Seri', disabled: false)
Designation.create( id: 12, code: 'tun', name: 'Tun', disabled: false)
Designation.create( id: 13, code: 'tsri', name: 'Tan Sri', disabled: false)
Designation.create( id: 14, code: 'prof', name: 'Prof.', disabled: false)
Designation.create( id: 15, code: 'profm', name: 'Prof. Madya', disabled: false)
Designation.create( id: 16, code: 'dr', name: 'Dr.', disabled: false)

Rnstat.create( id: 1, code: 'A', name: 'Active', disabled: false)
Rnstat.create( id: 2, code: 'X', name: 'Archive', disabled: false)

Patientstat.create( id: 1, code: 'A', name: 'Active', disabled: false)
Patientstat.create( id: 2, code: 'I', name: 'Inactive', disabled: false)

Treatmentstat.create( id: 1, code: 'N', name: 'New', disabled: false)
Treatmentstat.create( id: 2, code: 'C', name: 'Completed', disabled: false)
Treatmentstat.create( id: 3, code: 'B', name: 'Brough In Dead', disabled: false)

Discipline.create( id: 1, code: 'MEDICAL', name: 'MEDICAL', disabled: false)
Discipline.create( id: 2, code: 'SURGICAL', name: 'SURGICAL', disabled: false)
Discipline.create( id: 3, code: 'OBSTETRIC', name: 'OBSTETRIC', disabled: false)
Discipline.create( id: 4, code: 'PAEDIATRIC', name: 'PAEDIATRIC', disabled: false)
Discipline.create( id: 5, code: 'INFANT', name: 'INFANT', disabled: false)
Discipline.create( id: 6, code: 'UNCLASSIFIED', name: 'UNCLASSIFIED', disabled: false)
Discipline.create( id: 7, code: 'GYNAECOLOGY', name: 'GYNAECOLOGY', disabled: false)
Discipline.create( id: 8, code: 'ORTHOPAEDIC', name: 'ORTHOPAEDIC', disabled: false)
Discipline.create( id: 9, code: 'ENT', name: 'ENT', disabled: false)
Discipline.create( id: 10, code: 'OPHTALMOLOGY', name: 'OPHTALMOLOGY', disabled: false)
Discipline.create( id: 11, code: 'PLASTIC SURGERY', name: 'PLASTIC SURGERY', disabled: false)
Discipline.create( id: 12, code: 'DENTAL', name: 'DENTAL', disabled: false)
Discipline.create( id: 13, code: 'NEUROSURGEON', name: 'NEUROSURGEON', disabled: false)
Discipline.create( id: 14, code: 'ANESTHESIOLOGY', name: 'ANESTHESIOLOGY', disabled: false)
Discipline.create( id: 15, code: 'PSYCHIATRIC', name: 'PSYCHIATRIC', disabled: false)
Discipline.create( id: 16, code: 'RADIOLOGY', name: 'RADIOLOGY', disabled: false)
Discipline.create( id: 17, code: 'GENERAL SURGEON', name: 'GENERAL SURGEON', disabled: false)
Discipline.create( id: 18, code: 'OBSTETRIC & GYNECOLOGY', name: 'OBSTETRIC & GYNECOLOGY', disabled: false)
Discipline.create( id: 19, code: 'MO', name: 'Medical Officer', disabled: false)
Discipline.create( id: 20, code: 'CARDIOLOGY', name: 'CARDIOLOGY', disabled: false)
Discipline.create( id: 21, code: 'UROLOGY', name: 'UROLOGY', disabled: false)

Chargegroup.create( id: 22, code: 'PROCEDURE CHARGES', name: 'PROCEDURE CHARGES', disabled: false)
Chargegroup.create( id: 23, code: 'CSSD CHARGES', name: 'CSSD CHARGES', disabled: false)
Chargegroup.create( id: 24, code: 'OPERATION CHARGES', name: 'OPERATION CHARGES', disabled: false)
Chargegroup.create( id: 25, code: 'CONSULTATION FEES', name: 'CONSULTATION FEES', disabled: false)
Chargegroup.create( id: 26, code: 'ENDOSCOPIC EXAMINATION', name: 'ENDOSCOPIC EXAMINATION', disabled: false)
Chargegroup.create( id: 27, code: 'LABORATORY TESTS', name: 'LABORATORY TESTS', disabled: false)
Chargegroup.create( id: 28, code: 'ULTRASOUND CHARGES', name: 'ULTRASOUND CHARGES', disabled: false)
Chargegroup.create( id: 29, code: 'WARD TESTS', name: 'WARD TESTS', disabled: false)
Chargegroup.create( id: 30, code: 'RADIOLOGY CHARGES', name: 'RADIOLOGY CHARGES', disabled: false)
Chargegroup.create( id: 32, code: 'HOUSE CALL FEE', name: 'HOUSE CALL FEE', disabled: false)
Chargegroup.create( id: 33, code: 'AMBULANCE CHARGES', name: 'AMBULANCE CHARGES', disabled: false)
Chargegroup.create( id: 34, code: 'NURSING CHARGES', name: 'NURSING CHARGES', disabled: false)
Chargegroup.create( id: 35, code: 'HAEMODIALYSIS CHARGES', name: 'HAEMODIALYSIS CHARGES', disabled: false)
Chargegroup.create( id: 36, code: 'NURSERY CHARGES', name: 'NURSERY CHARGES', disabled: false)
Chargegroup.create( id: 37, code: 'LABOUR ROOM CHARGES', name: 'LABOUR ROOM CHARGES', disabled: false)
Chargegroup.create( id: 38, code: 'MISCELLANEOUS CHARGES', name: 'MISCELLANEOUS CHARGES', disabled: false)
Chargegroup.create( id: 39, code: 'CSSD-ORTHO', name: 'CSSD-ORTHO', disabled: false)
Chargegroup.create( id: 40, code: 'OT NURSING', name: 'OT NURSING', disabled: false)
Chargegroup.create( id: 41, code: 'D&C PACKAGE', name: 'D&C PACKAGE', disabled: false)
Chargegroup.create( id: 42, code: 'PHYSIOTHERAPY CHARGES', name: 'PHYSIOTHERAPY CHARGES', disabled: false)
Chargegroup.create( id: 43, code: 'PHARMACEUTICAL CHARGES', name: 'PHARMACEUTICAL CHARGES', disabled: false)
Chargegroup.create( id: 44, code: 'ROUNDING', name: 'ROUNDING', disabled: false)
Chargegroup.create( id: 47, code: 'K.DELV', name: 'DELIVERY PACKAGE', disabled: false)
Chargegroup.create( id: 48, code: 'K.CIRC', name: 'CIRCUMCISION PACKAGE', disabled: false)
Chargegroup.create( id: 49, code: 'K.IUCD', name: 'IUCD PACKAGE', disabled: false)
Chargegroup.create( id: 50, code: 'K.MC01', name: 'PRE-EMPLOYMENT M/CHK', disabled: false)
Chargegroup.create( id: 51, code: 'K.MC02', name: 'SENIOR CITIZEN PCKG', disabled: false)
Chargegroup.create( id: 52, code: 'K.MC03', name: 'EXEC M/CHCK - MO', disabled: false)
Chargegroup.create( id: 53, code: 'K.MC04', name: 'COLLEGE ENTRANCE M/C', disabled: false)
Chargegroup.create( id: 54, code: 'K.MC05', name: 'HAJJ/UMRAH M/CHK', disabled: false)
Chargegroup.create( id: 55, code: 'K.MC06', name: 'EXEC M/CHK - SPCLST', disabled: false)
Chargegroup.create( id: 56, code: 'K.OG01', name: 'ANTENATAL EXAM 1ST', disabled: false)
Chargegroup.create( id: 57, code: 'K.MC07', name: 'FULL EXEC M/CHK-SPCL', disabled: false)
Chargegroup.create( id: 58, code: 'K.OG02', name: 'ANTENATAL EXAM 2ND', disabled: false)
Chargegroup.create( id: 59, code: 'K.OG03', name: 'ANTENATAL EXAM SUBSQ', disabled: false)
Chargegroup.create( id: 60, code: 'K.MC08', name: 'FEMALE MEDICAL EXAM', disabled: false)
Chargegroup.create( id: 61, code: 'K.DLCS', name: 'DELVRY LSCS SPI EMER', disabled: false)
Chargegroup.create( id: 62, code: 'K.DLGA', name: 'DELVRY LSCS EMERGCY', disabled: false)
Chargegroup.create( id: 63, code: 'K.IMMU', name: 'IMMUNIZATION PACKAGE', disabled: false)
Chargegroup.create( id: 64, code: 'K.DLEA', name: 'DELVRY LSCS ELECTIVE', disabled: false)
Chargegroup.create( id: 65, code: 'K.DLES', name: 'DELVRY LSCS SPNAL EL', disabled: false)
Chargegroup.create( id: 66, code: 'K.DLEE', name: 'HERNIOPLASTY PACKAGE', disabled: false)
Chargegroup.create( id: 67, code: 'K.CIRS', name: 'CIRCUM SEDATION PCKG', disabled: false)
Chargegroup.create( id: 68, code: 'DEP', name: 'DEPOSIT', disabled: false)
Chargegroup.create( id: 69, code: 'REG3', name: 'ADMISSION FEE', disabled: false)
Chargegroup.create( id: 70, code: 'REG1', name: 'REGISTRATION FEE 1ST', disabled: false)
Chargegroup.create( id: 71, code: 'REG2', name: 'REGISTRATION FEE SUB', disabled: false)
Chargegroup.create( id: 72, code: 'TAX', name: 'TAX', disabled: false)
Chargegroup.create( id: 45, code: 'MEDICAL SUPPLIES', name: 'MEDICAL SUPPLIES', disabled: false)
Chargegroup.create( id: 74, code: 'INTERNAL FIXATION', name: 'INTERNAL FIXATION', disabled: false)
Chargegroup.create( id: 75, code: 'EXTERNAL FIXATION', name: 'EXTERNAL FIXATION', disabled: false)
Chargegroup.create( id: 77, code: 'AMEX', name: 'AMEX', disabled: false)
Chargegroup.create( id: 82, code: 'CHEQUE', name: 'CHEQUE', disabled: false)
Chargegroup.create( id: 83, code: 'POUT', name: 'PAY 0UT', disabled: false)
Chargegroup.create( id: 76, code: 'ANAESTHETIST FEE', name: 'ANAESTHETIST FEE', disabled: false)
Chargegroup.create( id: 31, code: 'ROOM CHARGES', name: 'ROOM CHARGE', disabled: false)
Chargegroup.create( id: 78, code: 'CASH', name: 'CASH PAYMENT', disabled: false)
Chargegroup.create( id: 79, code: 'CC', name: 'CREDIT CARD', disabled: false)
Chargegroup.create( id: 81, code: 'DB', name: 'DEBIT CARD/BANKCARD', disabled: false)
Chargegroup.create( id: 84, code: 'MEDICAL CHECKUP', name: 'MEDICAL EXAMINATION', disabled: false)
Chargegroup.create( id: 85, code: 'TAKE HOME DRUGS', name: 'TAKE HOME DRUGS', disabled: false)
Chargegroup.create( id: 86, code: 'ANAESTHETIC ASSESMENT', name: 'ANAESTHETIC ASSESMENT', disabled: false)
Chargegroup.create( id: 87, code: 'OPERATING THEATRE', name: 'OPERATING THEATRE', disabled: false)
Chargegroup.create( id: 88, code: 'DEBIT FROM SN', name: 'DEBIT FROM SN', disabled: false)
Chargegroup.create( id: 89, code: 'DEBIT TO SN', name: 'DEBIT TO SN', disabled: false)
Chargegroup.create( id: 90, code: 'DISCOUNT', name: 'DISCOUNT', disabled: false)
Chargegroup.create( id: 91, code: 'XX', name: 'A/R LEDGER', disabled: false)
Chargegroup.create( id: 92, code: 'KBMC', name: 'EXP-', disabled: false)
Chargegroup.create( id: 93, code: 'PATLEDGER', name: 'PATIENT LEDGER', disabled: false)
Chargegroup.create( id: 94, code: 'XXS', name: 'A/R LEDGER (S)', disabled: false)
Chargegroup.create( id: 95, code: 'DIFF', name: 'A/R DIFF', disabled: false)
Chargegroup.create( id: 96, code: 'DTDL', name: 'DEBIT TO DEBTOR LEDGER', disabled: false)
Chargegroup.create( id: 97, code: 'DRAW BLOOD', name: 'DRAW BLOOD', disabled: false)
Chargegroup.create( id: 98, code: 'COLLECT URINE', name: 'COLLECT URINE', disabled: false)
Chargegroup.create( id: 73, code: 'REP', name: 'MEDICAL REPORT', disabled: false)
Chargegroup.create( id: 100, code: 'IBG', name: 'Inter-Bank GIRO (IBG) Transfer', disabled: false)

Billingstat.create( id: 1, code: 'N', name: 'New', disabled: false)
Billingstat.create( id: 2, code: 'C', name: 'Completed', disabled: false)
Billingstat.create( id: 3, code: 'X', name: 'Cancelled', disabled: false)
Billingstat.create( id: 4, code: 'R', name: 'Archive', disabled: false)

Billitemstat.create( id: 1, code: 'A', name: 'Active', disabled: false)
Billitemstat.create( id: 2, code: 'I', name: 'Void', disabled: false)
Billitemstat.create( id: 3, code: 'C', name: 'Clear', disabled: false)
Billitemstat.create( id: 4, code: 'S', name: 'Suspend', disabled: false)

Postat.create( id: 1, code: 'O', name: 'Order', disabled: false)
Postat.create( id: 2, code: 'A', name: 'Acquired', disabled: false)
Postat.create( id: 3, code: 'D', name: 'Draft', disabled: false)
Postat.create( id: 4, code: 'C', name: 'Cancelled', disabled: false)

Drugprocedure.create( id: 1, code: 'A', name: 'Selepas Makan', disabled: false)
Drugprocedure.create( id: 2, code: 'B', name: 'Sebelum Makan', disabled: false)
Drugprocedure.create( id: 3, code: 'C', name: '', disabled: false)


Pricetype.create( id: 1, code: 'W', name: 'Warehouse', disabled: false)
Pricetype.create( id: 2, code: 'X', name: 'General', disabled: false)
Pricetype.create( id: 4, code: 'R', name: 'Lab Report', disabled: false)

Treatmentnotetype.create( id: 1, code: 'H', name: 'HOPI', disabled: false)
Treatmentnotetype.create( id: 2, code: 'N', name: 'Nursing Note', disabled: false)
Treatmentnotetype.create( id: 3, code: 'L', name: 'Lab Note', disabled: false)

Workorder.create( id: 1, code: 'REG', name: 'Registration', disabled: false)
Workorder.create( id: 2, code: 'TRI', name: 'Triage', disabled: false)
Workorder.create( id: 3, code: 'DOC', name: 'Doctor Consultation', disabled: false)
Workorder.create( id: 4, code: 'MOF', name: 'Medical Officer', disabled: false)
Workorder.create( id: 5, code: 'PHA', name: 'Pharmacy', disabled: false)
Workorder.create( id: 6, code: 'LAB', name: 'Lab', disabled: false)
Workorder.create( id: 7, code: 'TRM', name: 'Treatment Room', disabled: false)
Workorder.create( id: 8, code: 'BIL', name: 'Billing', disabled: false)

Workflowtemplate.create( id: 1, code: 'DEF', name: 'Default Template', disabled: false)

Workflowtemplateitem.create( id: 1, workflowtemplate_id: 1, workorder_id: 1,  sequence: 1)
Workflowtemplateitem.create( id: 2, workflowtemplate_id: 1, workorder_id: 3,  sequence: 2)
Workflowtemplateitem.create( id: 3, workflowtemplate_id: 1, workorder_id: 5,  sequence: 3)
Workflowtemplateitem.create( id: 4, workflowtemplate_id: 1, workorder_id: 8,  sequence: 4)

Workflowstat.create( id: 1, code: 'N', name: 'New', disabled: false)
Workflowstat.create( id: 2, code: 'C', name: 'Completed', disabled: false)

Role.create( id: 1, code: 'SYS', name: 'System Admin', disabled: false)
Role.create( id: 2, code: 'ADM', name: 'Administrator', disabled: false)
Role.create( id: 3, code: 'MD', name: 'Medical Doctor', disabled: false)
Role.create( id: 4, code: 'CS', name: 'Cashier', disabled: false)
Role.create( id: 5, code: 'PH', name: 'Pharmacist', disabled: false)
Role.create( id: 6, code: 'CL', name: 'Clerk', disabled: false)
Role.create( id: 7, code: 'NR', name: 'Staff Nurse', disabled: false)

Userstat.create( id: 1, code: 'A', name: 'Active', disabled: false)
Userstat.create( id: 2, code: 'D', name: 'Disabled', disabled: false)

Department.create( id: 1, code: 'M', name: 'Medical', disabled: false)

Inventorytype.create( id: 1, code: 'DRG', name: 'Drug', disabled: false)
Inventorytype.create( id: 2, code: 'DIS', name: 'Disposible Item', disabled: false)
Inventorytype.create( id: 3, code: 'NUT', name: 'Nutritions', disabled: false)

Labtemplate.create( id: 16, code: 'L-NEONATAL SCREENING', name: 'NEONATAL SCREENING', disabled: false)
Labtemplate.create( id: 24, code: 'L-VIRAL SEROLOGY', name: 'VIRAL SEROLOGY', disabled: false)
Labtemplate.create( id: 3, code: 'L-CHOLESTROL TEST', name: 'CHOLESTROL TEST', disabled: false)
Labtemplate.create( id: 4, code: 'L-BUSE', name: 'BUSE', disabled: false)
Labtemplate.create( id: 1, code: 'L-CLINICAL', name: 'CLINICAL', disabled: false)
Labtemplate.create( id: 2, code: 'L-HAEMATOLOGY', name: 'HAEMATOLOGY', disabled: false)
Labtemplate.create( id: 30, code: 'L-WIDAL-WEIL FELIX TEST', name: 'WIDAL-WEIL FELIX TEST', disabled: false)
Labtemplate.create( id: 6, code: 'L-ANTENATAL SCREENING', name: 'ANTENATAL SCREENING', disabled: false)
Labtemplate.create( id: 20, code: 'L-PROTEIN STUDY', name: 'PROTEIN STUDY', disabled: false)
Labtemplate.create( id: 11, code: 'L-COAGULATION STUDY', name: 'COAGULATION STUDY', disabled: false)
Labtemplate.create( id: 21, code: 'L-DENGUE SEROLOGY', name: 'DENGUE SEROLOGY', disabled: false)
Labtemplate.create( id: 36, code: 'L-FBC HAEMOTOLOGY (M)', name: 'FBC HAEMOTOLOGY (M)', disabled: false)
Labtemplate.create( id: 18, code: 'L-PAP SMEAR REPORT', name: 'PAP SMEAR REPORT', disabled: false)
Labtemplate.create( id: 9, code: 'L-SEMINAL ANALYSIS', name: 'SEMINAL ANALYSIS', disabled: false)
Labtemplate.create( id: 28, code: 'L-GLUCOSE TOLERANCE TEST (GTT)', name: 'GLUCOSE TOLERANCE TEST (GTT)', disabled: false)
Labtemplate.create( id: 33, code: 'L-LIPIDS STUDY/CORONARY RISK', name: 'LIPIDS STUDY/CORONARY RISK', disabled: false)
Labtemplate.create( id: 29, code: 'L-GLYCATED HAEMOGLOBIN (HbA1C)', name: 'GLYCATED HAEMOGLOBIN (HbA1C)', disabled: false)
Labtemplate.create( id: 10, code: 'L-ARTERIAL BLOOD GASES', name: 'ARTERIAL BLOOD GASES', disabled: false)
Labtemplate.create( id: 35, code: 'L-OTHERS', name: 'OTHERS', disabled: false)
Labtemplate.create( id: 23, code: 'L-ASOT SCREENING', name: 'ASOT SCREENING', disabled: false)
Labtemplate.create( id: 37, code: 'L-FBC HAEMOTOLOGY (F)', name: 'FBC HAEMOTOLOGY (F)', disabled: false)
Labtemplate.create( id: 32, code: 'L-MODIFIED GLUCOSE TOLERANCE TEST', name: 'MODIFIED GLUCOSE TOLERANCE TEST', disabled: false)
Labtemplate.create( id: 19, code: 'L-THYROID STUDIES', name: 'THYROID STUDIES', disabled: false)
Labtemplate.create( id: 14, code: 'L-LIVER FUNCTION TEST', name: 'LIVER FUNCTION TEST', disabled: false)
Labtemplate.create( id: 13, code: 'L-FULL BLOOD COUNT (FBC) (NEW BORN)', name: 'FULL BLOOD COUNT (FBC) (NEW BORN)', disabled: false)
Labtemplate.create( id: 12, code: 'L-FULL BLOOD COUNT (FBC) (6 MONTHS - 1 YEARS)', name: 'FULL BLOOD COUNT (FBC) (6 MONTHS -1 YEARS)', disabled: false)
Labtemplate.create( id: 7, code: 'L-CARDIAC ENZYMES', name: 'CARDIAC ENZYMES', disabled: false)
Labtemplate.create( id: 5, code: 'L-URINE FEME', name: 'URINE FEME', disabled: false)
Labtemplate.create( id: 17, code: 'L-DRUGS SCREENING', name: 'DRUGS SCREENING', disabled: false)
Labtemplate.create( id: 22, code: 'L-MICROALBUMIN', name: 'MICROALBUMIN', disabled: false)
Labtemplate.create( id: 40, code: 'L-DENGUE Ns1 ANTIGEN', name: 'DENGUE Ns1 ANTIGEN', disabled: false)
Labtemplate.create( id: 25, code: 'L-CREATININE CLEARANCE TEST', name: 'CREATININE CLEARANCE TEST', disabled: false)
Labtemplate.create( id: 26, code: 'L-GENERAL SCREENING PROFILE', name: 'GENERAL SCREENING PROFILE', disabled: false)
Labtemplate.create( id: 31, code: 'L-SALMONELLA TYPHI ANTIBODY', name: 'SALMONELLA TYPHI ANTIBODY', disabled: false)
Labtemplate.create( id: 27, code: 'L-FULL BLOOD COUNT (FBC) (1 - 6 YEARS)', name: 'FULL BLOOD COUNT (FBC) (1 - 6 YEARS)', disabled: false)
Labtemplate.create( id: 39, code: 'L-LEPTOSPIROSIS SEROLOGY', name: 'LEPTOSPIROSIS SEROLOGY', disabled: false)
Labtemplate.create( id: 15, code: 'L-RENAL FUNCTION TEST', name: 'RENAL FUNCTION TEST', disabled: false)
Labtemplate.create( id: 8, code: 'L-SERUM BILIRUBIN NNJ', name: 'SERUM BILIRUBIN NNJ', disabled: false)
Labtemplate.create( id: 41, code: 'L-SERUM AMYLASE', name: 'SERUM AMYLASE', disabled: false)
Labtemplate.create( id: 42, code: 'L-ARTHRITIS PROFILE', name: 'ARTHRITIS PROFILE', disabled: false)
Labtemplate.create( id: 43, code: 'L-ERYTHROCYTE SENDIMENTATION RATE', name: 'ERYTHROCYTE SENDIMENTATION RATE', disabled: false)



Labitem.create( id: 1, code: 'L-Haemoglobin (HB)', name: 'Haemoglobin (HB)', unit: '', normalvalue: '11.5-16.0', disabled: false)
Labitem.create( id: 2, code: 'L-VDRL Screening', name: 'VDRL Screening', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 3, code: 'L-Blood Grouping', name: 'Blood Grouping', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 4, code: 'L-pH', name: 'pH', unit: '', normalvalue: '7.35-7.45', disabled: false)
Labitem.create( id: 5, code: 'L-pCO2', name: 'pCO2', unit: '', normalvalue: '35-45', disabled: false)
Labitem.create( id: 6, code: 'L-pO2', name: 'pO2', unit: '', normalvalue: '80-95', disabled: false)
Labitem.create( id: 7, code: 'L-HCO3', name: 'HCO3', unit: '', normalvalue: '22-26', disabled: false)
Labitem.create( id: 8, code: 'L-Base Excess', name: 'Base Excess', unit: '', normalvalue: '0-2', disabled: false)
Labitem.create( id: 9, code: 'L-O2 Saturation', name: 'O2 Saturation', unit: '', normalvalue: '96-97', disabled: false)
Labitem.create( id: 10, code: 'L-ASOT', name: 'ASOT', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 11, code: 'L-UREA', name: 'UREA', unit: '', normalvalue: '1.7-9.1', disabled: false)
Labitem.create( id: 12, code: 'L-NA', name: 'NA', unit: '', normalvalue: '132-145', disabled: false)
Labitem.create( id: 13, code: 'L-K', name: 'K', unit: '', normalvalue: '3.5-5.1', disabled: false)
Labitem.create( id: 14, code: 'L-CL', name: 'CL', unit: '', normalvalue: '93-111', disabled: false)
Labitem.create( id: 15, code: 'L-CK', name: 'CK', unit: '', normalvalue: '24-195', disabled: false)
Labitem.create( id: 16, code: 'L-LDH', name: 'LDH', unit: '', normalvalue: '230-460', disabled: false)
Labitem.create( id: 17, code: 'L-SGOT', name: 'SGOT', unit: '', normalvalue: '40', disabled: false)
Labitem.create( id: 18, code: 'L-Prothrombin Time [PT]', name: 'Prothrombin Time [PT]', unit: '', normalvalue: '11.0-16.0', disabled: false)
Labitem.create( id: 19, code: 'L-APTT', name: 'APTT', unit: '', normalvalue: '24.0-36.0', disabled: false)
Labitem.create( id: 20, code: 'L-INR', name: 'INR', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 21, code: 'L-Urine Volume  (ml)', name: 'Urine Volume  (ml)', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 22, code: 'L-Collection Period (Hr)', name: 'Collection Period (Hr)', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 23, code: 'L-Serum Creatinine', name: 'Serum Creatinine', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 24, code: 'L-Urine Creatinine', name: 'Urine Creatinine', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 25, code: 'L-Creatinine Excretion', name: 'Creatinine Excretion', unit: '', normalvalue: '8.8-17.6', disabled: false)
Labitem.create( id: 26, code: 'L-Clearance', name: 'Clearance', unit: '', normalvalue: '1.5-2.5', disabled: false)
Labitem.create( id: 27, code: 'L-Dengue IgG Antibody', name: 'Dengue IgG Antibody', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 28, code: 'L-Dengue IgM Antibody', name: 'Dengue IgM Antibody', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 29, code: 'L-Screening for Urinary Morphine/Heroin derivatives', name: 'Screening for Urinary Morphine/Heroin derivatives', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 30, code: 'L-Screening for Urinary Cannabinoids', name: 'Screening for Urinary Cannabinoids', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 31, code: 'L-Haemoglobin (HB)', name: 'Haemoglobin (HB)', unit: '', normalvalue: '9.9-14.5', disabled: false)
Labitem.create( id: 32, code: 'L-TRBC', name: 'TRBC', unit: '', normalvalue: '3.8-5.2', disabled: false)
Labitem.create( id: 33, code: 'L-TWBC', name: 'TWBC', unit: '', normalvalue: '5.0-9.0', disabled: false)
Labitem.create( id: 34, code: 'L-PCV', name: 'PCV', unit: '', normalvalue: '29-43', disabled: false)
Labitem.create( id: 35, code: 'L-MCV', name: 'MCV', unit: '', normalvalue: '73-87', disabled: false)
Labitem.create( id: 36, code: 'L-MCH', name: 'MCH', unit: '', normalvalue: '24-30', disabled: false)
Labitem.create( id: 37, code: 'L-MCHC', name: 'MCHC', unit: '', normalvalue: '32-36', disabled: false)
Labitem.create( id: 38, code: 'L-Platelets', name: 'Platelets', unit: '', normalvalue: '150-400', disabled: false)
Labitem.create( id: 39, code: 'L-ESR [M]', name: 'ESR [M]', unit: '', normalvalue: '0-10', disabled: false)
Labitem.create( id: 40, code: 'L-ESR[F]', name: 'ESR[F]', unit: '', normalvalue: '0-15', disabled: false)
Labitem.create( id: 41, code: 'L-Neutrophils', name: 'Neutrophils', unit: '', normalvalue: '13-33', disabled: false)
Labitem.create( id: 42, code: 'L-Lymphocytes', name: 'Lymphocytes', unit: '', normalvalue: '46-76', disabled: false)
Labitem.create( id: 43, code: 'L-Monocytes', name: 'Monocytes', unit: '', normalvalue: '0-5', disabled: false)
Labitem.create( id: 44, code: 'L-Eosinophils', name: 'Eosinophils', unit: '', normalvalue: '0-3', disabled: false)
Labitem.create( id: 45, code: 'L-Basophils', name: 'Basophils', unit: '', normalvalue: '0-1', disabled: false)
Labitem.create( id: 46, code: 'L-Haemoglobin (HB)', name: 'Haemoglobin (HB)', unit: '', normalvalue: '9.5-14.3', disabled: false)
Labitem.create( id: 47, code: 'L-TRBC', name: 'TRBC', unit: '', normalvalue: '3.9-5.3', disabled: false)
Labitem.create( id: 48, code: 'L-TWBC', name: 'TWBC', unit: '', normalvalue: '5.0-19.0', disabled: false)
Labitem.create( id: 49, code: 'L-PCV', name: 'PCV', unit: '', normalvalue: '30-40', disabled: false)
Labitem.create( id: 50, code: 'L-MCV', name: 'MCV', unit: '', normalvalue: '70-84', disabled: false)
Labitem.create( id: 51, code: 'L-MCH', name: 'MCH', unit: '', normalvalue: '23-29', disabled: false)
Labitem.create( id: 52, code: 'L-MCHC', name: 'MCHC', unit: '', normalvalue: '31-35', disabled: false)
Labitem.create( id: 53, code: 'L-Platelets', name: 'Platelets', unit: '', normalvalue: '150-400', disabled: false)
Labitem.create( id: 54, code: 'L-Neutrophils', name: 'Neutrophils', unit: '', normalvalue: '13-33', disabled: false)
Labitem.create( id: 55, code: 'L-Lymphocytes', name: 'Lymphocytes', unit: '', normalvalue: '46-76', disabled: false)
Labitem.create( id: 56, code: 'L-Monocytes', name: 'Monocytes', unit: '', normalvalue: '0-5', disabled: false)
Labitem.create( id: 57, code: 'L-Eosinophils', name: 'Eosinophils', unit: '', normalvalue: '0-3', disabled: false)
Labitem.create( id: 58, code: 'L-Basophils', name: 'Basophils', unit: '', normalvalue: '0-1', disabled: false)
Labitem.create( id: 59, code: 'L-Haemoglobin (HB)', name: 'Haemoglobin (HB)', unit: '', normalvalue: '14.5-24.5', disabled: false)
Labitem.create( id: 60, code: 'L-TRBC', name: 'TRBC', unit: '', normalvalue: '4.10-6.10', disabled: false)
Labitem.create( id: 61, code: 'L-TWBC', name: 'TWBC', unit: '', normalvalue: '9.00-30.0', disabled: false)
Labitem.create( id: 62, code: 'L-PCV', name: 'PCV', unit: '', normalvalue: '44-64', disabled: false)
Labitem.create( id: 63, code: 'L-MCV', name: 'MCV', unit: '', normalvalue: '98-112', disabled: false)
Labitem.create( id: 64, code: 'L-MCH', name: 'MCH', unit: '', normalvalue: '34-40', disabled: false)
Labitem.create( id: 65, code: 'L-MCHC', name: 'MCHC', unit: '', normalvalue: '33-37', disabled: false)
Labitem.create( id: 66, code: 'L-Platelet', name: 'Platelet', unit: '', normalvalue: '150-400', disabled: false)
Labitem.create( id: 67, code: 'L-Neutrophils', name: 'Neutrophils', unit: '', normalvalue: '32-62', disabled: false)
Labitem.create( id: 68, code: 'L-Lymphocytes', name: 'Lymphocytes', unit: '', normalvalue: '26-36', disabled: false)
Labitem.create( id: 69, code: 'L-Monocytes', name: 'Monocytes', unit: '', normalvalue: '0-6', disabled: false)
Labitem.create( id: 70, code: 'L-Eosinophils', name: 'Eosinophils', unit: '', normalvalue: '0-2', disabled: false)
Labitem.create( id: 71, code: 'L-T.Proteins', name: 'T.Proteins', unit: '', normalvalue: '67 - 85', disabled: false)
Labitem.create( id: 72, code: 'L-Albumin', name: 'Albumin', unit: '', normalvalue: '37 - 51', disabled: false)
Labitem.create( id: 73, code: 'L-Globulin', name: 'Globulin', unit: '', normalvalue: '28 - 36', disabled: false)
Labitem.create( id: 74, code: 'L-A/G Ratio', name: 'A/G Ratio', unit: '', normalvalue: '0.9 - 1.8', disabled: false)
Labitem.create( id: 75, code: 'L-T.Bilirubin', name: 'T.Bilirubin', unit: '', normalvalue: '3.4 - 24.0', disabled: false)
Labitem.create( id: 76, code: 'L-Calcium', name: 'Calcium', unit: '', normalvalue: '2.1 - 2.8', disabled: false)
Labitem.create( id: 77, code: 'L-Inorganic Phos.', name: 'Inorganic Phos.', unit: '', normalvalue: '0.6 - 1.4', disabled: false)
Labitem.create( id: 78, code: 'L-Alkaline Phos', name: 'Alkaline Phos', unit: '', normalvalue: '36 - 92', disabled: false)
Labitem.create( id: 79, code: 'L-SGOT', name: 'SGOT', unit: '', normalvalue: '7.0-40', disabled: false)
Labitem.create( id: 80, code: 'L-SGPT', name: 'SGPT', unit: '', normalvalue: '4.0-54', disabled: false)
Labitem.create( id: 81, code: 'L-Glucose', name: 'Glucose', unit: '', normalvalue: '3.8 - 6.1', disabled: false)
Labitem.create( id: 82, code: 'L-Cholesterol', name: 'Cholesterol', unit: '', normalvalue: '3.1 - 6.5', disabled: false)
Labitem.create( id: 83, code: 'L-HDL-Cholesterol', name: 'HDL-Cholesterol', unit: '', normalvalue: '1.1 - 1.9', disabled: false)
Labitem.create( id: 84, code: 'L-LDL-Cholesterol', name: 'LDL-Cholesterol', unit: '', normalvalue: '3.9', disabled: false)
Labitem.create( id: 85, code: 'L-Triglycerides', name: 'Triglycerides', unit: '', normalvalue: '0.6 - 1.7', disabled: false)
Labitem.create( id: 86, code: 'L-Uric Acid(M)', name: 'Uric Acid(M)', unit: '', normalvalue: '416', disabled: false)
Labitem.create( id: 87, code: 'L-Uric Acid(F)', name: 'Uric Acid(F)', unit: '', normalvalue: '339', disabled: false)
Labitem.create( id: 88, code: 'L-Urea', name: 'Urea', unit: '', normalvalue: '2.3 - 6.8', disabled: false)
Labitem.create( id: 89, code: 'L-Na', name: 'Na', unit: '', normalvalue: '132 - 145', disabled: false)
Labitem.create( id: 90, code: 'L-K', name: 'K', unit: '', normalvalue: '3.5 - 5.1', disabled: false)
Labitem.create( id: 91, code: 'L-Cl', name: 'Cl', unit: '', normalvalue: '93 - 108', disabled: false)
Labitem.create( id: 92, code: 'L-Creatinine (M)', name: 'Creatinine (M)', unit: '', normalvalue: '44 - 124', disabled: false)
Labitem.create( id: 93, code: 'L-Creatinine (F)', name: 'Creatinine (F)', unit: '', normalvalue: ' 44 - 89', disabled: false)
Labitem.create( id: 94, code: 'L-Haemoglobin (HB) (M)', name: 'Haemoglobin (HB) (M)', unit: '', normalvalue: '13.5 - 18.0', disabled: false)
Labitem.create( id: 95, code: 'L-Haemoglobin (HB) (F)', name: 'Haemoglobin (HB) (F)', unit: '', normalvalue: '11.5 - 16.0', disabled: false)
Labitem.create( id: 96, code: 'L-TRBC (M)', name: 'TRBC (M)', unit: '', normalvalue: '4.5 - 6.5', disabled: false)
Labitem.create( id: 97, code: 'L-TRBC (F)', name: 'TRBC (F)', unit: '', normalvalue: '3.9 - 5.6', disabled: false)
Labitem.create( id: 98, code: 'L-TWBC', name: 'TWBC', unit: '', normalvalue: '4.0-11.0', disabled: false)
Labitem.create( id: 99, code: 'L-PCV (M)', name: 'PCV (M)', unit: '', normalvalue: '40-54', disabled: false)
Labitem.create( id: 100, code: 'L-PCV (F)', name: 'PCV (F)', unit: '', normalvalue: '35 - 47', disabled: false)
Labitem.create( id: 101, code: 'L-MCV', name: 'MCV', unit: '', normalvalue: '27 - 32', disabled: false)
Labitem.create( id: 102, code: 'L-MCH', name: 'MCH', unit: '', normalvalue: '27 - 32', disabled: false)
Labitem.create( id: 103, code: 'L-MCHC', name: 'MCHC', unit: '', normalvalue: '30-35', disabled: false)
Labitem.create( id: 104, code: 'L-Platelet', name: 'Platelet', unit: '', normalvalue: '150-400', disabled: false)
Labitem.create( id: 105, code: 'L-Neutrophils', name: 'Neutrophils', unit: '', normalvalue: '40-75', disabled: false)
Labitem.create( id: 106, code: 'L-Lymphocytes', name: 'Lymphocytes', unit: '', normalvalue: '20 - 45', disabled: false)
Labitem.create( id: 107, code: 'L-Monocytes ', name: 'Monocytes ', unit: '', normalvalue: '2.0-10', disabled: false)
Labitem.create( id: 108, code: 'L-Eosinophils', name: 'Eosinophils', unit: '', normalvalue: '1.0-6.0', disabled: false)
Labitem.create( id: 109, code: 'L-Basophils', name: 'Basophils', unit: '', normalvalue: '0-1', disabled: false)
Labitem.create( id: 110, code: 'L-pH ', name: 'pH ', unit: '', normalvalue: '7', disabled: false)
Labitem.create( id: 111, code: 'L-Specific Gravity', name: 'Specific Gravity', unit: '', normalvalue: '1.005-1.03', disabled: false)
Labitem.create( id: 112, code: 'L-Proteins', name: 'Proteins', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 113, code: 'L-Glucose', name: 'Glucose', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 114, code: 'L-Ketones', name: 'Ketones', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 115, code: 'L-Bilirubin', name: 'Bilirubin', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 116, code: 'L-Urobilinogen', name: 'Urobilinogen', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 117, code: 'L-Nitirite', name: 'Nitirite', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 118, code: 'L-RBC', name: 'RBC', unit: '', normalvalue: '0-1', disabled: false)
Labitem.create( id: 119, code: 'L-wbc', name: 'wbc', unit: '', normalvalue: '0-3', disabled: false)
Labitem.create( id: 120, code: 'L-bacteria', name: 'bacteria', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 121, code: 'L-Epithelial Cells', name: 'Epithelial Cells', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 122, code: 'L-Cast', name: 'Cast', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 123, code: 'L-Crystals', name: 'Crystals', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 124, code: 'L-Others', name: 'Others', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 125, code: 'L-Coulours', name: 'Coulours', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 126, code: 'L-Transperancy', name: 'Transperancy', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 127, code: 'L-Glucose [F]', name: 'Glucose [F]', unit: '', normalvalue: '3.0-6.5', disabled: false)
Labitem.create( id: 128, code: 'L-Glucose [1HPP]', name: 'Glucose [1HPP]', unit: '', normalvalue: '10', disabled: false)
Labitem.create( id: 129, code: 'L-Glucose [2HPP]', name: 'Glucose [2HPP]', unit: '', normalvalue: '7.8', disabled: false)
Labitem.create( id: 130, code: 'L- HbA1C', name: ' HbA1C', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 131, code: 'L-Salmonella Typhi \'O\' (TO)', name: 'Salmonella Typhi \'O\' (TO)', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 132, code: 'L-Salmonella Typhi \'H\' (TH)', name: 'Salmonella Typhi \'H\' (TH)', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 133, code: 'L-Salmonella Paratyphi \'A\'(AH)', name: 'Salmonella Paratyphi \'A\'(AH)', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 134, code: 'L-Salmonella Paratyphi \'B\'(BH)', name: 'Salmonella Paratyphi \'B\'(BH)', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 135, code: 'L-Proteus OXK', name: 'Proteus OXK', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 136, code: 'L-Proteus OX19', name: 'Proteus OX19', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 137, code: 'L- HSV Type I IgM Antibody', name: ' HSV Type I IgM Antibody', unit: '', normalvalue: '9.0-11.0', disabled: false)
Labitem.create( id: 138, code: 'L-pH', name: 'pH', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 139, code: 'L-Specific Gravity', name: 'Specific Gravity', unit: '', normalvalue: '1.005 - 1.030', disabled: false)
Labitem.create( id: 140, code: 'L-Proteins', name: 'Proteins', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 141, code: 'L-Glucose', name: 'Glucose', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 142, code: 'L-Ketones', name: 'Ketones', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 143, code: 'L-Bilirubin', name: 'Bilirubin', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 144, code: 'L-Urobilinogen', name: 'Urobilinogen', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 145, code: 'L-Nitrite', name: 'Nitrite', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 146, code: 'L-RBC', name: 'RBC', unit: '', normalvalue: '0-1', disabled: false)
Labitem.create( id: 147, code: 'L-WBC', name: 'WBC', unit: '', normalvalue: '0-3', disabled: false)
Labitem.create( id: 148, code: 'L-Epithelial Cells', name: 'Epithelial Cells', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 149, code: 'L-Cast ', name: 'Cast ', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 150, code: 'L-Crystals', name: 'Crystals', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 151, code: 'L-Bacteria', name: 'Bacteria', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 152, code: 'L-Others', name: 'Others', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 153, code: 'L-Colour', name: 'Colour', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 154, code: 'L-Transparency', name: 'Transparency', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 155, code: 'L-Free  T4', name: 'Free  T4', unit: '', normalvalue: '12.0-22.0', disabled: false)
Labitem.create( id: 156, code: 'L-Free  T3', name: 'Free  T3', unit: '', normalvalue: '3.0-6.5', disabled: false)
Labitem.create( id: 157, code: 'L-TSH', name: 'TSH', unit: '', normalvalue: '0.30-5.50', disabled: false)
Labitem.create( id: 158, code: 'L-Collection Time', name: 'Collection Time', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 159, code: 'L-Receiving Time', name: 'Receiving Time', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 160, code: 'L-Place of Collection', name: 'Place of Collection', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 161, code: 'L-Volume', name: 'Volume', unit: '', normalvalue: '2.0 - 7.0', disabled: false)
Labitem.create( id: 162, code: 'L-Reaction/pH', name: 'Reaction/pH', unit: '', normalvalue: '7.2 - 8.5', disabled: false)
Labitem.create( id: 163, code: 'L-Colour(Greyish/Opaque White)', name: 'Colour(Greyish/Opaque White)', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 164, code: 'L-Consistency  (Gelatinous)', name: 'Consistency  (Gelatinous)', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 165, code: 'L-Motility', name: 'Motility', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 166, code: 'L-Vigorously Active', name: 'Vigorously Active', unit: '', normalvalue: '75-80', disabled: false)
Labitem.create( id: 167, code: 'L-Medium Active', name: 'Medium Active', unit: '', normalvalue: '75-80', disabled: false)
Labitem.create( id: 168, code: 'L-Non-motile/Dead', name: 'Non-motile/Dead', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 169, code: 'L-Sperm Count', name: 'Sperm Count', unit: '', normalvalue: '60-300', disabled: false)
Labitem.create( id: 170, code: 'L-Liquefaction Time (< 1 Hr)', name: 'Liquefaction Time (< 1 Hr)', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 171, code: 'L-Microscopy WBC', name: 'Microscopy WBC', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 172, code: 'L-Microscopy Epithelial Cell', name: 'Microscopy Epithelial Cell', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 173, code: 'L-Others', name: 'Others', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 174, code: 'L-Morphlogy Oval/Normal', name: 'Morphlogy Oval/Normal', unit: '', normalvalue: '31 - 98', disabled: false)
Labitem.create( id: 175, code: 'L-Morphlogy Tapering', name: 'Morphlogy Tapering', unit: '', normalvalue: '0 - 59', disabled: false)
Labitem.create( id: 176, code: 'L-Morphlogy Round form', name: 'Morphlogy Round form', unit: '', normalvalue: '0 - 9', disabled: false)
Labitem.create( id: 177, code: 'L-Morphlogy Duplicate', name: 'Morphlogy Duplicate', unit: '', normalvalue: '0 - 17', disabled: false)
Labitem.create( id: 178, code: 'L-Morphlogy Giant/pinhead', name: 'Morphlogy Giant/pinhead', unit: '', normalvalue: '0 - 8', disabled: false)
Labitem.create( id: 179, code: 'L-Morphlogy Amorphous', name: 'Morphlogy Amorphous', unit: '', normalvalue: '0 - 12', disabled: false)
Labitem.create( id: 180, code: 'L-SALMONELLA TYPHI IgG ANTIBODY', name: 'SALMONELLA TYPHI IgG ANTIBODY', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 181, code: 'L-SALMONELLA TYPHI IgM ANTIBODY', name: 'SALMONELLA TYPHI IgM ANTIBODY', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 182, code: 'L-S.Typhi IgM Positive', name: 'S.Typhi IgM Positive', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 183, code: 'L-S.Typhi IgM & IgG Positive', name: 'S.Typhi IgM & IgG Positive', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 184, code: 'L-S.Typhi IgG Positive', name: 'S.Typhi IgG Positive', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 185, code: 'L-T.Proteins', name: 'T.Proteins', unit: '', normalvalue: '66-87', disabled: false)
Labitem.create( id: 186, code: 'L-Calcium', name: 'Calcium', unit: '', normalvalue: '2.0-2.6', disabled: false)
Labitem.create( id: 187, code: 'L-Inorganic Phos.', name: 'Inorganic Phos.', unit: '', normalvalue: '0.8-1.6', disabled: false)
Labitem.create( id: 188, code: 'L-Glucose (F)', name: 'Glucose (F)', unit: '', normalvalue: '3.8-6.1', disabled: false)
Labitem.create( id: 189, code: 'L-Glucose ( R )', name: 'Glucose ( R )', unit: '', normalvalue: '4.0-7.8', disabled: false)
Labitem.create( id: 190, code: 'L-Cholesterol', name: 'Cholesterol', unit: '', normalvalue: '3.1-5.2', disabled: false)
Labitem.create( id: 191, code: 'L-Uric Acid (MALE)', name: 'Uric Acid (MALE)', unit: '', normalvalue: '416', disabled: false)
Labitem.create( id: 192, code: 'L-Uric Acid (FEMALE)', name: 'Uric Acid (FEMALE)', unit: '', normalvalue: '339', disabled: false)
Labitem.create( id: 193, code: 'L-Sodium (Na)', name: 'Sodium (Na)', unit: '', normalvalue: '137-150', disabled: false)
Labitem.create( id: 194, code: 'L-Potassium (K)', name: 'Potassium (K)', unit: '', normalvalue: '3.5-5.2', disabled: false)
Labitem.create( id: 195, code: 'L-Chloride (Cl)', name: 'Chloride (Cl)', unit: '', normalvalue: '94-111', disabled: false)
Labitem.create( id: 196, code: 'L-Creatinine (MALE)', name: 'Creatinine (MALE)', unit: '', normalvalue: '44-124', disabled: false)
Labitem.create( id: 197, code: 'L-Creatinine (FEMALE)', name: 'Creatinine (FEMALE)', unit: '', normalvalue: '44-89', disabled: false)
Labitem.create( id: 198, code: 'L-Urea', name: 'Urea', unit: '', normalvalue: '1.7-9.1', disabled: false)
Labitem.create( id: 199, code: 'L-pH', name: 'pH', unit: '', normalvalue: '7', disabled: false)
Labitem.create( id: 200, code: 'L-Specific Gravity', name: 'Specific Gravity', unit: '', normalvalue: '1.005-1.030', disabled: false)
Labitem.create( id: 201, code: 'L-Protein', name: 'Protein', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 202, code: 'L-Glucose', name: 'Glucose', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 203, code: 'L-Ketones', name: 'Ketones', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 204, code: 'L-Bilirubin', name: 'Bilirubin', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 205, code: 'L-Urobilinogen', name: 'Urobilinogen', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 206, code: 'L-Nitrite', name: 'Nitrite', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 207, code: 'L-RBC', name: 'RBC', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 208, code: 'L-WBC', name: 'WBC', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 209, code: 'L-Epithelial Cells', name: 'Epithelial Cells', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 210, code: 'L-Cast', name: 'Cast', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 211, code: 'L-Crystal', name: 'Crystal', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 212, code: 'L-Bacteria', name: 'Bacteria', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 213, code: 'L-Others', name: 'Others', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 214, code: 'L-Colour', name: 'Colour', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 215, code: 'L-Transparency', name: 'Transparency', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 216, code: 'L-CRP', name: 'CRP', unit: '', normalvalue: '12', disabled: false)
Labitem.create( id: 217, code: 'L-CYTOLOGY NO.', name: 'CYTOLOGY NO.', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 218, code: 'L-HORMONAL PATTERN', name: 'HORMONAL PATTERN', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 219, code: 'L-BACTERIAL FLORA', name: 'BACTERIAL FLORA', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 220, code: 'L-INFLAMMATION', name: 'INFLAMMATION', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 221, code: 'L-SPECIFIC INFECTION', name: 'SPECIFIC INFECTION', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 222, code: 'L-LEUCOCYTES', name: 'LEUCOCYTES', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 223, code: 'L-EPITHELIAL CHANGES', name: 'EPITHELIAL CHANGES', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 224, code: 'L-CLASS', name: 'CLASS', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 225, code: 'L-SMEAR', name: 'SMEAR', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 226, code: 'L-G6PD', name: 'G6PD', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 227, code: 'L-Blood Group', name: 'Blood Group', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 228, code: 'L-Rh(D)', name: 'Rh(D)', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 229, code: 'L-Pre-Breakfast', name: 'Pre-Breakfast', unit: '', normalvalue: '3.0-6.5', disabled: false)
Labitem.create( id: 230, code: 'L-Pre-Lunch', name: 'Pre-Lunch', unit: '', normalvalue: '4.0-7.8', disabled: false)
Labitem.create( id: 231, code: 'L-Pre-Dinner', name: 'Pre-Dinner', unit: '', normalvalue: '4.0-7.8', disabled: false)
Labitem.create( id: 232, code: 'L-10.00 PM', name: '10.00 PM', unit: '', normalvalue: '4.0-7.8', disabled: false)
Labitem.create( id: 233, code: 'L-Urinary Albumin Excretion', name: 'Urinary Albumin Excretion', unit: '', normalvalue: '20', disabled: false)
Labitem.create( id: 234, code: 'L-Normalbuminuria', name: 'Normalbuminuria', unit: '', normalvalue: '20', disabled: false)
Labitem.create( id: 235, code: 'L-Microalbuminuria', name: 'Microalbuminuria', unit: '', normalvalue: '20-200', disabled: false)
Labitem.create( id: 236, code: 'L-Persistent proteinuria', name: 'Persistent proteinuria', unit: '', normalvalue: '200', disabled: false)
Labitem.create( id: 237, code: 'L-T.Proteins', name: 'T.Proteins', unit: '', normalvalue: '66-87', disabled: false)
Labitem.create( id: 238, code: 'L-Albumin', name: 'Albumin', unit: '', normalvalue: '38-50', disabled: false)
Labitem.create( id: 239, code: 'L-Globulin', name: 'Globulin', unit: '', normalvalue: '18-42', disabled: false)
Labitem.create( id: 240, code: 'L-A/G Ratio', name: 'A/G Ratio', unit: '', normalvalue: '1.0-2.2', disabled: false)
Labitem.create( id: 241, code: 'L-T.Bilirubin', name: 'T.Bilirubin', unit: '', normalvalue: '3.4-24.0', disabled: false)
Labitem.create( id: 242, code: 'L-Alkaline Phos.', name: 'Alkaline Phos.', unit: '', normalvalue: '36-110', disabled: false)
Labitem.create( id: 243, code: 'L-SGOT', name: 'SGOT', unit: '', normalvalue: '16-40', disabled: false)
Labitem.create( id: 244, code: 'L-SGPT', name: 'SGPT', unit: '', normalvalue: '8.0-54', disabled: false)
Labitem.create( id: 245, code: 'L-GGT', name: 'GGT', unit: '', normalvalue: '11.0-63', disabled: false)
Labitem.create( id: 246, code: 'L-Cholesterol', name: 'Cholesterol', unit: '', normalvalue: '3.1-5.2', disabled: false)
Labitem.create( id: 247, code: 'L-Triglycerides', name: 'Triglycerides', unit: '', normalvalue: '0.6-2.3', disabled: false)
Labitem.create( id: 248, code: 'L-HDL-Chol', name: 'HDL-Chol', unit: '', normalvalue: '1.1-1.9', disabled: false)
Labitem.create( id: 249, code: 'L-LDL-Chol', name: 'LDL-Chol', unit: '', normalvalue: '3.9', disabled: false)
Labitem.create( id: 250, code: 'L-Haemoglobin (HB) (M)', name: 'Haemoglobin (HB) (M)', unit: '', normalvalue: '13.5-18.0', disabled: false)
Labitem.create( id: 251, code: 'L-Haemoglobin (HB) (F)', name: 'Haemoglobin (HB) (F)', unit: '', normalvalue: '11.5-16.0', disabled: false)
Labitem.create( id: 252, code: 'L-TRBC (M)', name: 'TRBC (M)', unit: '', normalvalue: '4.5-6.5', disabled: false)
Labitem.create( id: 253, code: 'L-TRBC (F)', name: 'TRBC (F)', unit: '', normalvalue: '3.9-5.6', disabled: false)
Labitem.create( id: 254, code: 'L-TWBC', name: 'TWBC', unit: '', normalvalue: '4.0-11.0', disabled: false)
Labitem.create( id: 255, code: 'L-PCV (M)', name: 'PCV (M)', unit: '', normalvalue: '40-54', disabled: false)
Labitem.create( id: 256, code: 'L-PCV (F)', name: 'PCV (F)', unit: '', normalvalue: '35-47', disabled: false)
Labitem.create( id: 257, code: 'L-MCV', name: 'MCV', unit: '', normalvalue: '80-97', disabled: false)
Labitem.create( id: 258, code: 'L-MCH', name: 'MCH', unit: '', normalvalue: '27-32', disabled: false)
Labitem.create( id: 259, code: 'L-MCHC', name: 'MCHC', unit: '', normalvalue: '30-35', disabled: false)
Labitem.create( id: 260, code: 'L-Platelet', name: 'Platelet', unit: '', normalvalue: '150-400', disabled: false)
Labitem.create( id: 261, code: 'L-ESR (M)', name: 'ESR (M)', unit: '', normalvalue: '0-10', disabled: false)
Labitem.create( id: 262, code: 'L-ESR (F)', name: 'ESR (F)', unit: '', normalvalue: '0-15', disabled: false)
Labitem.create( id: 263, code: 'L-Reticulocytes', name: 'Reticulocytes', unit: '', normalvalue: '0.2-2.0', disabled: false)
Labitem.create( id: 264, code: 'L-Neutrophils', name: 'Neutrophils', unit: '', normalvalue: '40-75', disabled: false)
Labitem.create( id: 265, code: 'L-Lymphocytes', name: 'Lymphocytes', unit: '', normalvalue: '20-45', disabled: false)
Labitem.create( id: 266, code: 'L-Monocytes', name: 'Monocytes', unit: '', normalvalue: '2.0-10', disabled: false)
Labitem.create( id: 267, code: 'L-Eosinophils', name: 'Eosinophils', unit: '', normalvalue: '1.0-6', disabled: false)
Labitem.create( id: 268, code: 'L-Basophils', name: 'Basophils', unit: '', normalvalue: '0', disabled: false)
Labitem.create( id: 269, code: 'L-HT43', name: 'mamat', unit: '', normalvalue: '', disabled: false)
Labitem.create( id: 270, code: 'L-HT42', name: 'laaa', unit: '', normalvalue: '0', disabled: false)

Gstcode.create( id: 1, code: 'SR', name: 'Standard-rated supplies with GST Charged.', rate: 6, gsttype: 'SUPPLY', disabled: false)
Gstcode.create( id: 2, code: 'ZRL', name: 'Local supply of goods or services which are subject to zero rated supplies.', rate: 0, gsttype: 'SUPPLY', disabled: false)
Gstcode.create( id: 3, code: 'ZRE', name: 'Exportation of goods or services which are subject to zero rated supplies.', rate: 0, gsttype: 'SUPPLY', disabled: false)
Gstcode.create( id: 4, code: 'ES43', name: 'Incidental Exempt supplies.', rate: 0, gsttype: 'SUPPLY', disabled: false)
Gstcode.create( id: 5, code: 'DS', name: 'Deemed supplies (e.g. transfer or disposal of business assets without consideration).', rate: 6, gsttype: 'SUPPLY', disabled: false)
Gstcode.create( id: 6, code: 'OS', name: 'Out-of-scope supplies.', rate: 0, gsttype: 'SUPPLY', disabled: false)
Gstcode.create( id: 7, code: 'ES43', name: 'Exempt supplies under GST', rate: 0, gsttype: 'SUPPLY', disabled: false)
Gstcode.create( id: 8, code: 'RS', name: 'Relief supply under GST.', rate: 0, gsttype: 'SUPPLY', disabled: false)
Gstcode.create( id: 9, code: 'GS', name: 'Disregarded supplies.', rate: 0, gsttype: 'SUPPLY', disabled: false)
Gstcode.create( id: 10, code: 'AJS', name: 'Any adjustment made to Output Tax e.g : Longer period adjustment, Bad Debt recover, outstanding invoice > 6 months& other output tax adjustments.', rate: 6, gsttype: 'SUPPLY', disabled: false)
Gstcode.create( id: 11, code: 'TX', name: 'Purchases with GST incurred at 6% and directly attributable to taxable supplies.', rate: 6, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 12, code: 'IM', name: 'Import of goods with GST incurred.', rate: 6, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 13, code: 'IS', name: 'Imports under special scheme with no GST incurred (e.g. Approved Trader Scheme, ATMS Scheme).', rate: 0, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 14, code: 'BL', name: 'Purchases with GST incurred but not claimable (Disallowance of Input Tax) (e.g. medical expenses for staff).', rate: 6, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 15, code: 'NR', name: 'Purchase from non GST-registered supplier with no GST incurred.', rate: 0, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 16, code: 'ZP', name: 'Purchase from GST-registered supplier with no GST incurred. (e.g. supplier provides transportation of goods that qualify as international services).', rate: 0, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 17, code: 'EP', name: 'Purchases exempted from GST. E.g. purchase of residential property or financial services.', rate: 0, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 18, code: 'OP', name: 'Purchase transactions which is out of the scope of GST legislation (e.g. purchase of goods overseas).', rate: 0, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 19, code: 'TX-E43', name: 'Purchase with GST incurred directly attributable to incidental exempt supplies.', rate: 6, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 20, code: 'TX-N43', name: 'Purchase with GST incurred directly attributable to non-incidental exempt supplies.', rate: 6, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 21, code: 'TX-RE', name: 'Purchase with GST incurred that is not directly attributable to taxable or exempt supplies.', rate: 6, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 22, code: 'GP', name: 'Purchase transactions which disregarded under GST legislation (e.g. purchase within GST group registration).', rate: 0, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 23, code: 'AJP', name: 'Any adjustment made to Input Tax e.g.: Bad Debt Relief & other input tax adjustment.', rate: 6, gsttype: 'PURCHASE', disabled: false)
Gstcode.create( id: 24, code: 'TX-CG', name: 'Capital goods acquired. (BOX 16)', rate: 6, gsttype: 'PURCHASE', disabled: false)

Documentstat.create( id: 1, code: 'A', name: 'Active', disabled: false)
Documentstat.create( id: 2, code: 'X', name: 'Cancelled', disabled: false)

Icdtype.create( id: 1, code: 'ICD10', name: 'ICD10 Universal', disabled: false)
Icdtype.create( id: 2, code: 'ICD10-CM', name: 'ICD10 Clinical Modification', disabled: false)
Icdtype.create( id: 3, code: 'ICD10-PCS', name: 'ICD10 Procedure Coding System', disabled: false)

Medicationstat.create( id: 1, code: 'O', name: 'Order', disabled: false)
Medicationstat.create( id: 2, code: 'G', name: 'Given', disabled: false)
Medicationstat.create( id: 3, code: 'C', name: 'Cancelled', disabled: false)

Audittype.create( id: 1, code: 'AUTH', name: 'Authentication Audit', disabled: false)
Audittype.create( id: 2, code: 'GENERAL', name: 'General Audit', disabled: false)
